# Get team rosters for a season

In [ ]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

In [ ]:
import pandas as pd
import requests

In [ ]:
def get_teams_for_season_id(season_id):
  teams_response = requests.get("https://lscluster.hockeytech.com/feed/index.php?feed=modulekit&view=teamsbyseason&season_id="+ str(season_id)+"&key=446521baf8c38984&client_code=pwhl")
  if teams_response.status_code != 200:
    return None

  teams_json = teams_response.json()
  teams_list = teams_json["SiteKit"]["Teamsbyseason"]

  # Load the JSON file into a DataFrame
  teams_df = pd.json_normalize(teams_list)

  return teams_df

In [ ]:
get_teams_for_season_id(10)

,id,name,city,code,nickname,team_caption,division_id,division_long_name,division_short_name,team_logo_url
0,1,Boston Fleet,Boston,BOS,Fleet,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/1.png
1,2,Minnesota Frost,Minnesota,MIN,Frost,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/2.jpg
2,3,Montréal Victoire,Montréal,MTL,Victoire,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/3.png
3,4,New York Sirens,New York,NY,Sirens,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/4.png
4,5,Ottawa Charge,Ottawa,OTT,Charge,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/5.png
5,10,PWHL Detroit,Detroit,DET,PWHL,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/10.png
6,11,PWHL Hamilton,Hamilton,HAM,PWHL,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/11.png
7,12,PWHL Las Vegas,Las Vegas,LV,PWHL,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/12.png
8,13,PWHL San Jose,San Jose,SJ,PWHL,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/13.png
9,8,Seattle Torrent,Seattle,SEA,Torrent,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/8.png
10,6,Toronto Sceptres,Toronto,TOR,Sceptres,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/6.png
11,9,Vancouver Goldeneyes,Vancouver,VAN,Goldeneyes,,1,PWHL,PWHL,https://assets.leaguestat.com/pwhl/logos/9.png

In [ ]:
def get_roster_for_season_id_and_team_id(season_id, team_id):
  roster_response = requests.get("https://lscluster.hockeytech.com/feed/index.php?feed=modulekit&view=roster&team_id="+str(team_id)+"&season_id="+str(season_id)+"&key=446521baf8c38984&client_code=pwhl")
  if roster_response.status_code != 200:
    return None

  roster_json = roster_response.json()
  roster_list = roster_json["SiteKit"]["Roster"]
  roster_without_coaches = [item for item in roster_list if not isinstance(item, list)]

  # Load the JSON file into a DataFrame
  roster_df = pd.json_normalize(roster_without_coaches)

  return roster_df

In [ ]:
get_roster_for_season_id_and_team_id(1,3)

,id,person_id,active,first_name,last_name,phonetic_name,display_name,shoots,catches,hometown,...,position,nhlteam,playerId,isRookie,h,w,draft_status,draftinfo,name,player_image
0,166,201,1,Marlène,Boissonnault,,,L,L,"Dundee, NB",...,G,,166,&nbsp;,,0,,[],Marlène Boissonnault,https://assets.leaguestat.com/pwhl/240x240/166...
1,99,127,1,Mariah,Keopple,,,L,NaN,"Menomonie, WI",...,D,,99,*,5'9,0,,[],Mariah Keopple,https://assets.leaguestat.com/pwhl/240x240/99.jpg
2,177,371,1,Brooke,Stacey,,,L,NaN,,...,F,,177,&nbsp;,,,,[],Brooke Stacey,https://lscluster.hockeytech.com/img/nophoto.png
3,163,198,1,Catherine,Daoust,,,R,NaN,"L’Île-Bizard, QC",...,D,,163,&nbsp;,5'5,0,,[],Catherine Daoust,https://assets.leaguestat.com/pwhl/240x240/163...
4,162,197,1,Madison,Bizal,,,L,NaN,"Elk River, MN",...,D,,162,*,,0,,[],Madison Bizal,https://assets.leaguestat.com/pwhl/240x240/162...
5,32,34,1,Laura,Stacey,STAY-see,,R,NaN,"Kleinburg, ON",...,F,,32,&nbsp;,"5'10""",0,,[],Laura Stacey,https://assets.leaguestat.com/pwhl/240x240/32.jpg
6,156,191,1,Gabrielle,David,,,R,NaN,"Drummondville, QC",...,F,,156,*,5'4,0,,[],Gabrielle David,https://assets.leaguestat.com/pwhl/240x240/156...
7,84,103,1,Kati,Tabin,,,L,NaN,"Winnipeg, MB",...,D,,84,&nbsp;,"5'8""",0,,[],Kati Tabin,https://assets.leaguestat.com/pwhl/240x240/84.jpg
8,164,199,1,Brigitte,Laganière,,,L,NaN,"Montréal, QC",...,D,,164,&nbsp;,,,,[],Brigitte Laganière,https://assets.leaguestat.com/pwhl/240x240/164...
9,159,194,1,Leah,Lum,,,L,NaN,"Richmond, BC",...,F,,159,&nbsp;,,,,[],Leah Lum,https://assets.leaguestat.com/pwhl/240x240/159...
10,27,29,1,Jillian,Dempsey,JIH-lee-in DEHMP-see,,L,NaN,"Winthrop, MA",...,F,,27,&nbsp;,5'5,0,,[],Jillian Dempsey,https://assets.leaguestat.com/pwhl/240x240/27.jpg
11,98,126,1,Maureen,Murphy,,,R,NaN,"Buffalo, NY",...,F,,98,*,5'4,0,,[],Maureen Murphy,https://assets.leaguestat.com/pwhl/240x240/98.jpg
12,158,193,1,Sarah,Lefort,,,L,NaN,"Ormstown, QC",...,F,,158,&nbsp;,,,,[],Sarah Lefort,https://assets.leaguestat.com/pwhl/240x240/158...
13,160,195,1,Alexandra,Poznikoff,,,R,NaN,"Edmonton, AB",...,F,,160,&nbsp;,,,,[],Alexandra Poznikoff,https://assets.leaguestat.com/pwhl/240x240/160...
14,138,171,1,Mikyla,Grant-Mentis,,,L,NaN,"Brampton, ON",...,F,,138,&nbsp;,5'6,0,,[],Mikyla Grant-Mentis,https://assets.leaguestat.com/pwhl/240x240/138...
15,85,104,1,Elaine,Chuli,,,L,L,"Waterford, ON",...,G,,85,&nbsp;,5'7,0,,[],Elaine Chuli,https://assets.leaguestat.com/pwhl/240x240/85.jpg
16,161,196,1,Tereza,Vanišová,TAH-ree-zuh VAH-nee-soh-VUH,,L,NaN,"Strakonice, CZE",...,F,,161,&nbsp;,5'7,0,,[],Tereza Vanišová,https://assets.leaguestat.com/pwhl/240x240/161...
17,29,31,1,Kennedy,Marchment,,,R,NaN,"Marmora, ON",...,F,,29,&nbsp;,5'8,0,,[],Kennedy Marchment,https://assets.leaguestat.com/pwhl/240x240/29.jpg
18,83,102,1,Erin,Ambrose,,,R,NaN,"Keswick, ON",...,D,,83,&nbsp;,"5'5""",0,,[],Erin Ambrose,https://assets.leaguestat.com/pwhl/240x240/83.jpg
19,80,99,1,Ann-Sophie,Bettez,,,L,NaN,"Sept-Îles, QC",...,F,,80,&nbsp;,,,,[],Ann-Sophie Bettez,https://assets.leaguestat.com/pwhl/240x240/80.jpg
20,168,203,1,Mélodie,Daoust,,,L,NaN,"Valleyfield, QC",...,F,,168,&nbsp;,,,,[],Mélodie Daoust,https://assets.leaguestat.com/pwhl/240x240/168...
21,81,100,1,Sarah,Bujold,,,L,NaN,"Riverview, NB",...,F,,81,&nbsp;,,0,,[],Sarah Bujold,https://assets.leaguestat.com/pwhl/240x240/81.jpg
22,157,192,1,Catherine,Dubois,,,L,NaN,"Charlesbourg, QC",...,F,,157,&nbsp;,"5'10""",0,,[],Catherine Dubois,https://assets.leaguestat.com/pwhl/240x240/157...
23,31,33,1,Marie-Philip,Poulin,,,L,NaN,"Beauceville, QC",...,F,,31,&nbsp;,5'7,0,,[],Marie-Philip Poulin,https://assets.leaguestat.com/pwhl/240x240/31.jpg
24,139,172,1,Liliane,Perreault,,,R,NaN,"Hinsdale, IL",...,F,,139,&nbsp;,,,,[],Liliane Perreault,https://assets.leaguestat.com/pwhl/240x240/139...
25,28,30,1,Ann-Renée,Desbiens,,,L,L,"Clermont, QC",...,G,,28,&nbsp;,"5'9""",0,,[],Ann-Renée Desbiens,https://assets.leaguestat.com/pwhl/240x240/28.jpg
26,26,28,1,Claire,Dalton,,,R,NaN,"Toronto, ON",...,F,,26,*,"5'9""",0,,[],Claire Dalton,https://assets.leaguestat.com/pwhl/240x240/26.jpg
27,30,32,1,Kristin,O'Neill,,,L,NaN,"Oakville, ON",...,F,,30,&nbsp;,"5'4""",0,,[],Kristin O'Neill,https://assets.leaguestat.com/pwhl/240x240/30.jpg
28,51,53,1,Amanda,Boulier,,,R,NaN,"Watertown, CT",...,D,,51,&nbsp;,"5'1""",0,,[],Amanda Boulier,https://assets.leaguestat.com/pwhl/240x240/51.jpg
29,82,101,1,Dominika,Lásková,,,R,NaN,"Prague, CZE",...,D,,82,&nbsp;,5'6,0,,[],Dominika Lásková,https://assets.leaguestat.com/pwhl/240x240/82.jpg

# Get all team rosters for desired seasons

Also create a player ID map
`all_team_rosters, player_id_map = get_all_team_rosters()`

In [ ]:
def get_seasons():
  seasons_response = requests.get("https://lscluster.hockeytech.com/feed/index.php?feed=modulekit&view=seasons&key=446521baf8c38984&client_code=pwhl")
  if seasons_response.status_code != 200:
    return None

  seasons_json = seasons_response.json()
  seasons_list = seasons_json["SiteKit"]["Seasons"]

  # Load the JSON file into a DataFrame
  seasons_df = pd.json_normalize(seasons_list)

  return seasons_df

In [ ]:
get_seasons()

,season_id,season_name,shortname,career,playoff,start_date,end_date
0,10,2026-27 Pre-Season,2026-27 Pre-Season,0,0,2026-10-01,2026-11-30
1,9,2026 Playoffs,2026 Playoffs,1,1,2026-04-28,2026-05-28
2,8,2025-26 Regular Season,2025-26 Reg,1,0,2025-11-21,2026-04-27
3,7,2025-26 Preseason,2025-26 Preseason,0,0,2025-06-01,2025-11-19
4,6,2025 Playoffs,2025 Playoffs,1,1,2025-05-06,2025-06-03
5,5,2024-25 Regular Season,2024-25 Reg,1,0,2024-11-25,2025-05-05
6,4,2024-25 Preseason,2024-25 Preseason,0,0,2024-11-01,2024-11-29
7,3,2024 Playoffs,2024 Playoffs,1,1,2024-05-06,2024-06-10
8,1,2024 Regular Season,2024 Reg,1,0,2024-01-01,2024-05-27
9,2,2024 Preseason,2024 Preseason,0,0,2023-11-01,2023-12-31

In [ ]:
season_to_id_map = {
    "2024": 1,
    "2024-2025": 5,
    "2025-2026": 8,
    "2026-2027": 10,
}

In [ ]:
TORRENT_ID = 8

In [ ]:
# verify that we already have roster info for next season
get_roster_for_season_id_and_team_id(8,TORRENT_ID)

,id,person_id,active,first_name,last_name,phonetic_name,display_name,shoots,hometown,homeprov,...,nhlteam,playerId,isRookie,h,w,draft_status,draftinfo,name,player_image,catches
0,62,64,1,Aneta,Tejralová,AH-neh-TAH TEH-ruh-low-VAH,,L,"Prague, CZE",CZE,...,,62,&nbsp;,5'5,0,,[],Aneta Tejralová,https://assets.leaguestat.com/pwhl/240x240/62.jpg,NaN
1,196,392,1,Cayla,Barnes,,,R,"Eastvale, CA",CA,...,,196,&nbsp;,"5'2""",0,,[],Cayla Barnes,https://assets.leaguestat.com/pwhl/240x240/196...,NaN
2,203,399,1,Anna,Wilgren,,,L,"Hudson, WI",WI,...,,203,&nbsp;,"5'8""",0,,[],Anna Wilgren,https://assets.leaguestat.com/pwhl/240x240/203...,NaN
3,298,542,1,Emily,Zumwinkle,,,R,"Excelsior, MN",MN,...,,298,*,,0,,[],Emily Zumwinkle,https://assets.leaguestat.com/pwhl/240x240/298...,NaN
4,291,535,1,Lily,Delianedis,,,L,"Edina, MN",MN,...,,291,*,,0,,[],Lily Delianedis,https://assets.leaguestat.com/pwhl/240x240/291...,NaN
5,142,175,1,Natalie,Snodgrass,NAT-uh-lee SNAWD-grahs,,L,"Eagan, MN",,...,,142,&nbsp;,"5'6""",0,,[],Natalie Snodgrass,https://assets.leaguestat.com/pwhl/240x240/142...,NaN
6,237,476,1,Jenna,Buglioni,,,R,"Port Moody, BC",,...,,237,*,5'3,0,,[],Jenna Buglioni,https://assets.leaguestat.com/pwhl/240x240/237...,NaN
7,2,4,1,Emily,Brown,EHM-IHL-EE BROWN,,L,"Blaine, MN",Minnesota,...,,2,&nbsp;,5'7,0,,[],Emily Brown,https://assets.leaguestat.com/pwhl/240x240/2.jpg,NaN
8,138,171,1,Mikyla,Grant-Mentis,,,L,"Brampton, ON",,...,,138,&nbsp;,5'6,0,,[],Mikyla Grant-Mentis,https://assets.leaguestat.com/pwhl/240x240/138...,NaN
9,91,119,1,Brooke,Bryant,BRUHK BRIGH-uhnt,,R,"Linden, CA",California,...,,91,&nbsp;,5'6,0,,[],Brooke Bryant,https://assets.leaguestat.com/pwhl/240x240/91.jpg,NaN
10,181,377,1,Hannah,Bilka,HAN-uh BIHL-KUH,,L,"Coppell, TX",TX,...,,181,&nbsp;,5'5,0,,[],Hannah Bilka,https://assets.leaguestat.com/pwhl/240x240/181...,NaN
11,99,127,1,Mariah,Keopple,,,L,"Menomonie, WI",Wisconsin,...,,99,&nbsp;,5'9,0,,[],Mariah Keopple,https://assets.leaguestat.com/pwhl/240x240/99.jpg,NaN
12,294,538,1,Lyndie,Lobdell,,,R,"Aurora, IL",IL,...,,294,*,,0,,[],Lyndie Lobdell,https://assets.leaguestat.com/pwhl/240x240/294...,NaN
13,34,36,1,Alex,Carpenter,AL-ehx KAHR-pehn-tuhr,,L,"North Reading, MA",Massachusetts,...,,34,&nbsp;,"5'7""",0,,[],Alex Carpenter,https://assets.leaguestat.com/pwhl/240x240/34.jpg,NaN
14,208,404,1,Megan,Carter,MEH-gan CART-uhr,,L,"Milton, ON",ON,...,,208,&nbsp;,5'8,0,,[],Megan Carter,https://assets.leaguestat.com/pwhl/240x240/208...,NaN
15,156,191,1,Gabrielle,David,,,R,"Drummondville, QC",,...,,156,&nbsp;,5'4,0,,[],Gabrielle David,https://assets.leaguestat.com/pwhl/240x240/156...,NaN
16,155,188,1,Corinne,Schroeder,kohr-een SHROW-duhr,,R,"Elm Creek, MB",,...,,155,&nbsp;,"5'11""",0,,[],Corinne Schroeder,https://assets.leaguestat.com/pwhl/240x240/155...,L
17,17,19,1,Theresa,Schafzahl,TUH-reh-zuh SHAWF-zahl,,L,"Weiz, AUT",AUT,...,,17,&nbsp;,5'8,0,,[],Theresa Schafzahl,https://assets.leaguestat.com/pwhl/240x240/17.jpg,NaN
18,292,536,1,Jada,Habisch,,,R,"Buffalo, MN",MN,...,,292,*,,0,,[],Jada Habisch,https://assets.leaguestat.com/pwhl/240x240/292...,NaN
19,295,539,1,Marah,Wagner,,,L,"Seattle, WA",WA,...,,295,*,,0,,[],Marah Wagner,https://assets.leaguestat.com/pwhl/240x240/295...,NaN
20,134,167,1,Carly,Jackson,CAR-lee JAK-sun,,R,"Amherst, NS",,...,,134,&nbsp;,"5'5""",0,,[],Carly Jackson,https://assets.leaguestat.com/pwhl/240x240/134...,L
21,293,537,1,Sydney,Langseth,,,R,"Eden Prairie, MN",MN,...,,293,*,,0,,[],Sydney Langseth,https://assets.leaguestat.com/pwhl/240x240/293...,NaN
22,49,51,1,Lexie,Adzija,LEHKS-ee ah-JEE-uh,,L,"St. Thomas, ON",Ontario,...,,49,&nbsp;,5'10,0,"Ottawa (PWHL) 2023 Round: 11 (#65), Ottawa (PW...","[{'id': '295', 'person_id': '51', 'draft_round...",Lexie Adzija,https://assets.leaguestat.com/pwhl/240x240/49.jpg,NaN
23,250,490,1,Hannah,Murphy,,,R,"Kingston, ON",ON,...,,250,*,5'10,0,,[],Hannah Murphy,https://assets.leaguestat.com/pwhl/240x240/250...,L
24,210,406,1,Julia,Gosling,JOO-lee-uh GAWZ-lihng,,L,"London, ON",ON,...,,210,&nbsp;,"5'10""",0,,[],Julia Gosling,https://assets.leaguestat.com/pwhl/240x240/210...,NaN
25,224,420,1,Danielle,Serdachny,DAN-yehl suhr-DAK-nee,,R,"Edmonton, AB",AB,...,,224,&nbsp;,"5'9""",0,,[],Danielle Serdachny,https://assets.leaguestat.com/pwhl/240x240/224...,NaN

In [ ]:
def get_team_rosters_for_season_id(season_id):
  teams_df = get_teams_for_season_id(season_id)
  team_dict = {}
  for _, team in teams_df.iterrows():
    roster_df = get_roster_for_season_id_and_team_id(season_id, team["id"])
    roster_list = set(roster_df["name"].tolist())
    city_name = team["city"];
    if city_name == "Montreal":
      city_name = "Montréal"
    team_dict[city_name] = roster_list
  return team_dict

In [ ]:
s1_team_rosters = get_team_rosters_for_season_id(1)

In [ ]:
s1_team_rosters

{'Boston': {'Abby Cook',
  'Aerin Frankel',
  'Alina Müller',
  'Amanda Pelkey',
  'Caitrin Lonergan',
  'Cami Kronish',
  'Emily Brown',
  'Emma Buckles',
  'Emma Söderberg',
  'Gigi Marvin',
  'Hannah Brandt',
  'Hilary Knight',
  'Jamie Lee Rattray',
  'Jess Healey',
  'Jessica DiGirolamo',
  'Kaleigh Fratkin',
  'Kelly Babstock',
  'Lexie Adzija',
  'Loren Gabel',
  'Megan Keller',
  'Nicole Kosta',
  'Samantha Isbell',
  'Sammy Davis',
  'Shiann Darkangelo',
  'Sidney Morin',
  'Sophie Jaques',
  'Sophie Shirley',
  'Susanna Tapani',
  'Taylor Girard',
  'Taylor Wenczkowski',
  'Theresa Schafzahl'},
 'Minnesota': {'Abby Boreen',
  'Abby Cook',
  'Amanda Leveille',
  'Brittyn Fleming',
  'Brooke Bryant',
  'Clair DeGeorge',
  'Claire Butorac',
  'Denisa Křížová',
  'Dominique Kremer',
  'Emma Greco',
  'Grace Zumwinkle',
  'Kelly Pannek',
  'Kendall Coyne Schofield',
  'Lauren Bench',
  'Lee Stecklein',
  'Liz Schepers',
  'Maddie Rooney',
  'Maggie Flaherty',
  'Mellissa Channell-Watkins',
  'Michela Cava',
  'Natalie Buchbinder',
  'Nicole Hensley',
  'Nikki Nightengale',
  'Sophia Kunin',
  'Sophie Jaques',
  'Susanna Tapani',
  'Sydney Brodt',
  'Taylor Heise'},
 'Montréal': {'Alexandra Poznikoff',
  'Amanda Boulier',
  'Ann-Renée Desbiens',
  'Ann-Sophie Bettez',
  'Brigitte Laganière',
  'Brooke Stacey',
  'Catherine Daoust',
  'Catherine Dubois',
  'Claire Dalton',
  'Dominika Lásková',
  'Elaine Chuli',
  'Erin Ambrose',
  'Gabrielle David',
  'Jillian Dempsey',
  'Kati Tabin',
  'Kennedy Marchment',
  "Kristin O'Neill",
  'Laura Stacey',
  'Leah Lum',
  'Liliane Perreault',
  'Madison Bizal',
  'Mariah Keopple',
  'Marie-Philip Poulin',
  'Marlène Boissonnault',
  'Maureen Murphy',
  'Mikyla Grant-Mentis',
  'Mélodie Daoust',
  'Sarah Bujold',
  'Sarah Lefort',
  'Tereza Vanišová'},
 'New York': {'Abbey Levy',
  'Abby Roque',
  'Alex Carpenter',
  'Alexa Gruschow',
  'Alexandra Labelle',
  'Brooke Hobson',
  'Carley Olivier',
  'Chloé Aurard-Bushee',
  'Claire Thompson',
  'Corinne Schroeder',
  'Ella Shelton',
  'Emma Woods',
  'Jade Downie-Landry',
  'Jaime Bourbonnais',
  'Jessie Eldridge',
  'Jill Saulnier',
  'Johanna Fällman',
  'Kayla Vespa',
  'Lindsey Post',
  'Madison Packer',
  'Micah Zandee-Hart',
  'Olivia Zafuto',
  'Paetyn Levis',
  'Savannah Norcross',
  'Taylor Baker',
  'Élizabeth Giguère'},
 'Ottawa': {'Akane Shiga',
  'Amanda Boulier',
  'Aneta Tejralová',
  'Ashton Bell',
  'Audrey-Ann Veilette',
  'Becca Gilmore',
  'Brianne Jenner',
  'Daryl Watts',
  'Emerance Maschmeyer',
  'Emily Clark',
  'Emma Buckles',
  'Fanni Garát-Gasparics',
  'Gabbie Hughes',
  'Hayley Scamurra',
  'Jincy Roese',
  'Kateřina Mrázová',
  'Kristin Della Rovere',
  'Lauren MacInnis',
  'Lexie Adzija',
  'Malia Schneider',
  'Mikyla Grant-Mentis',
  'Natalie Snodgrass',
  'Rachel McQuigge',
  'Rosalie Demers',
  'Samantha Isbell',
  'Sammy Davis',
  'Sandra Abstreiter',
  'Savannah Harmon',
  'Shiann Darkangelo',
  'Taylor Davison',
  'Tereza Vanišová',
  'Victoria Howran',
  'Zoe Boyd'},
 'Toronto': {'Alexa Vasko',
  'Allie Munroe',
  'Blayre Turnbull',
  'Brittany Howard',
  'Carly Jackson',
  'Emma Keenan',
  'Emma Maltais',
  'Erica Howe',
  'Hannah Miller',
  'Jess Jones',
  'Jesse Compher',
  'Jessica Kondas',
  'Jocelyne Larocque',
  'Kaitlin Willoughby',
  'Kali Flanagan',
  'Kristen Campbell',
  'Lauriane Rougeau',
  'Maggie Connors',
  'Maude Poulin-Labelle',
  'Natalie Spooner',
  'Olivia Knowles',
  'Rebecca Leslie',
  'Renata Fast',
  'Samantha Cogan',
  'Sarah Nurse',
  'Victoria Bach'}}

In [ ]:
def get_all_team_rosters_1():
  season_team_roster_dict = {}
  for season_name in season_to_id_map.keys():
    team_rosters = get_team_rosters_for_season_id(season_to_id_map[season_name])
    season_team_roster_dict[season_name] = team_rosters
  return season_team_roster_dict

In [ ]:
all_team_rosters = get_all_team_rosters_1()

In [ ]:
def get_team_rosters_for_season_id(season_id):
  teams_df = get_teams_for_season_id(season_id)
  team_dict = {}
  player_id_map_for_season = {} # New: to store player name to ID mapping for this season

  for _, team in teams_df.iterrows():
    roster_df = get_roster_for_season_id_and_team_id(season_id, team["id"])
    if roster_df is not None and not roster_df.empty: # Check if roster_df is not None and not empty
        roster_list = set(roster_df["name"].tolist())
        # Populate player_id_map_for_season
        # Iterate over the roster_df to get both 'name' and 'person_id'
        for _, player_row in roster_df.iterrows():
            player_name = player_row["name"]
            player_id = player_row["id"]
            player_id_map_for_season[player_name] = player_id
    else:
        roster_list = set() # If no roster or empty, set an empty set

    city_name = team["city"]
    if city_name == "Montreal":
      city_name = "Montréal"
    team_dict[city_name] = roster_list
  return team_dict, player_id_map_for_season

def get_all_team_rosters():
  season_team_roster_dict = {}
  all_players_id_map = {} # New: to store player name to ID mapping across all seasons

  for season_name in season_to_id_map.keys():
    # Call the modified get_team_rosters_for_season_id
    team_rosters, player_id_map_for_season = get_team_rosters_for_season_id(season_to_id_map[season_name])
    season_team_roster_dict[season_name] = team_rosters
    all_players_id_map.update(player_id_map_for_season) # Update the master map

  return season_team_roster_dict, all_players_id_map

In [ ]:
all_team_rosters, player_id_map = get_all_team_rosters()

In [ ]:
all_team_rosters

{'2024': {'Boston': {'Abby Cook',
   'Aerin Frankel',
   'Alina Müller',
   'Amanda Pelkey',
   'Caitrin Lonergan',
   'Cami Kronish',
   'Emily Brown',
   'Emma Buckles',
   'Emma Söderberg',
   'Gigi Marvin',
   'Hannah Brandt',
   'Hilary Knight',
   'Jamie Lee Rattray',
   'Jess Healey',
   'Jessica DiGirolamo',
   'Kaleigh Fratkin',
   'Kelly Babstock',
   'Lexie Adzija',
   'Loren Gabel',
   'Megan Keller',
   'Nicole Kosta',
   'Samantha Isbell',
   'Sammy Davis',
   'Shiann Darkangelo',
   'Sidney Morin',
   'Sophie Jaques',
   'Sophie Shirley',
   'Susanna Tapani',
   'Taylor Girard',
   'Taylor Wenczkowski',
   'Theresa Schafzahl'},
  'Minnesota': {'Abby Boreen',
   'Abby Cook',
   'Amanda Leveille',
   'Brittyn Fleming',
   'Brooke Bryant',
   'Clair DeGeorge',
   'Claire Butorac',
   'Denisa Křížová',
   'Dominique Kremer',
   'Emma Greco',
   'Grace Zumwinkle',
   'Kelly Pannek',
   'Kendall Coyne Schofield',
   'Lauren Bench',
   'Lee Stecklein',
   'Liz Schepers',
   'Maddie Rooney',
   'Maggie Flaherty',
   'Mellissa Channell-Watkins',
   'Michela Cava',
   'Natalie Buchbinder',
   'Nicole Hensley',
   'Nikki Nightengale',
   'Sophia Kunin',
   'Sophie Jaques',
   'Susanna Tapani',
   'Sydney Brodt',
   'Taylor Heise'},
  'Montréal': {'Alexandra Poznikoff',
   'Amanda Boulier',
   'Ann-Renée Desbiens',
   'Ann-Sophie Bettez',
   'Brigitte Laganière',
   'Brooke Stacey',
   'Catherine Daoust',
   'Catherine Dubois',
   'Claire Dalton',
   'Dominika Lásková',
   'Elaine Chuli',
   'Erin Ambrose',
   'Gabrielle David',
   'Jillian Dempsey',
   'Kati Tabin',
   'Kennedy Marchment',
   "Kristin O'Neill",
   'Laura Stacey',
   'Leah Lum',
   'Liliane Perreault',
   'Madison Bizal',
   'Mariah Keopple',
   'Marie-Philip Poulin',
   'Marlène Boissonnault',
   'Maureen Murphy',
   'Mikyla Grant-Mentis',
   'Mélodie Daoust',
   'Sarah Bujold',
   'Sarah Lefort',
   'Tereza Vanišová'},
  'New York': {'Abbey Levy',
   'Abby Roque',
   'Alex Carpenter',
   'Alexa Gruschow',
   'Alexandra Labelle',
   'Brooke Hobson',
   'Carley Olivier',
   'Chloé Aurard-Bushee',
   'Claire Thompson',
   'Corinne Schroeder',
   'Ella Shelton',
   'Emma Woods',
   'Jade Downie-Landry',
   'Jaime Bourbonnais',
   'Jessie Eldridge',
   'Jill Saulnier',
   'Johanna Fällman',
   'Kayla Vespa',
   'Lindsey Post',
   'Madison Packer',
   'Micah Zandee-Hart',
   'Olivia Zafuto',
   'Paetyn Levis',
   'Savannah Norcross',
   'Taylor Baker',
   'Élizabeth Giguère'},
  'Ottawa': {'Akane Shiga',
   'Amanda Boulier',
   'Aneta Tejralová',
   'Ashton Bell',
   'Audrey-Ann Veilette',
   'Becca Gilmore',
   'Brianne Jenner',
   'Daryl Watts',
   'Emerance Maschmeyer',
   'Emily Clark',
   'Emma Buckles',
   'Fanni Garát-Gasparics',
   'Gabbie Hughes',
   'Hayley Scamurra',
   'Jincy Roese',
   'Kateřina Mrázová',
   'Kristin Della Rovere',
   'Lauren MacInnis',
   'Lexie Adzija',
   'Malia Schneider',
   'Mikyla Grant-Mentis',
   'Natalie Snodgrass',
   'Rachel McQuigge',
   'Rosalie Demers',
   'Samantha Isbell',
   'Sammy Davis',
   'Sandra Abstreiter',
   'Savannah Harmon',
   'Shiann Darkangelo',
   'Taylor Davison',
   'Tereza Vanišová',
   'Victoria Howran',
   'Zoe Boyd'},
  'Toronto': {'Alexa Vasko',
   'Allie Munroe',
   'Blayre Turnbull',
   'Brittany Howard',
   'Carly Jackson',
   'Emma Keenan',
   'Emma Maltais',
   'Erica Howe',
   'Hannah Miller',
   'Jess Jones',
   'Jesse Compher',
   'Jessica Kondas',
   'Jocelyne Larocque',
   'Kaitlin Willoughby',
   'Kali Flanagan',
   'Kristen Campbell',
   'Lauriane Rougeau',
   'Maggie Connors',
   'Maude Poulin-Labelle',
   'Natalie Spooner',
   'Olivia Knowles',
   'Rebecca Leslie',
   'Renata Fast',
   'Samantha Cogan',
   'Sarah Nurse',
   'Victoria Bach'}},
 '2024-2025': {'Boston': {'Aerin Frankel',
   'Alina Müller',
   'Amanda Pelkey',
   'Daniela Pejšová',
   'Emily Brown',
   'Emma Greco',
   'Emma Söderberg',
   'Hadley Hartmetz',
   'Hannah Bilka',
   'Hannah Brandt',
   'Hilary Knight',
   'Jamie Lee Rattray',
   'Jessica DiGirolamo',
   'Jill Saulnier',
   'Jillian Dempsey',
   'Kelly Babstock',
   'Klára Peslarová',
   'Lexie Adzija',
   'Loren Gabel',
   'Megan Keller',
   'Olivia Zafuto',
   'Shay Maloney',
   'Sidney Morin',
   'Sophie Shirley',
   'Susanna Tapani',
   'Sydney Bard',
   'Taylor Girard',
   'Theresa Schafzahl'},
  'Minnesota': {'Britta Curl-Salemme',
   'Brooke Bryant',
   'Brooke McQuigge',
   'Charlotte Akervik',
   'Claire Butorac',
   'Claire Thompson',
   'Denisa Křížová',
   'Dominique Petrie',
   'Grace Zumwinkle',
   "Kaitlyn O'Donohoe",
   'Katy Knoll',
   'Kelly Pannek',
   'Kendall Coyne Schofield',
   'Klára Hymlárová',
   'Lee Stecklein',
   'Liz Schepers',
   'Lucy Morgan',
   'Maddie Rooney',
   'Mae Batherson',
   'Maggie Flaherty',
   'Marlène Boissonnault',
   'Mellissa Channell-Watkins',
   'Michela Cava',
   'Natalie Buchbinder',
   'Nicole Hensley',
   'Sophie Jaques',
   'Taylor Heise'},
  'Montréal': {'Abby Boreen',
   'Alexandra Labelle',
   'Amanda Boulier',
   'Ann-Renée Desbiens',
   'Anna Kjellbin',
   'Anna Wilgren',
   'Catherine Daoust',
   'Catherine Dubois',
   'Cayla Barnes',
   'Clair DeGeorge',
   'Claire Dalton',
   'Dara Greig',
   'Dominika Lásková',
   'Elaine Chuli',
   'Erin Ambrose',
   'Gabrielle David',
   'Jenn Gardiner',
   'Kaitlin Willoughby',
   'Kati Tabin',
   'Kelly Ann Nadeau',
   'Kennedy Marchment',
   "Kristin O'Neill",
   'Laura Stacey',
   'Lina Ljungblom',
   'Mariah Keopple',
   'Marie-Philip Poulin',
   'Maureen Murphy',
   'Mikyla Grant-Mentis',
   'Sandra Abstreiter',
   'Tricia Deguire'},
  'New York': {'Abbey Levy',
   'Abby Roque',
   'Alex Carpenter',
   'Alexie Guay',
   'Allyson Simpson',
   'Brooke Hobson',
   'Chloé Aurard-Bushee',
   'Corinne Schroeder',
   'Ella Shelton',
   'Elle Hartje',
   'Emmy Fecteau',
   'Gabby Rosenthal',
   'Jade Downie-Landry',
   'Jaime Bourbonnais',
   'Jessie Eldridge',
   'Jill Saulnier',
   'Kayla Vespa',
   'Kayle Osborne',
   'Lauren Bernard',
   'Maja Nylén Persson',
   'Micah Zandee-Hart',
   'Noora Tulus',
   'Olivia Knowles',
   'Paetyn Levis',
   'Sarah Fillier',
   'Taylor Baker',
   'Taylor Girard',
   'Élizabeth Giguère'},
  'Ottawa': {'Alexa Vasko',
   'Aneta Tejralová',
   'Anna Meixner',
   'Ashton Bell',
   'Brianne Jenner',
   'Danielle Serdachny',
   'Emerance Maschmeyer',
   'Emily Clark',
   'Gabbie Hughes',
   'Gwyneth Philips',
   'Hayley Scamurra',
   'Jessica Adolfsson',
   'Jincy Roese',
   'Jocelyne Larocque',
   'Kateřina Mrázová',
   'Logan Angers',
   'Lucy Morgan',
   'Mannon McMahon',
   'Natalie Snodgrass',
   'Rebecca Leslie',
   'Ronja Savolainen',
   'Samantha Isbell',
   'Savannah Harmon',
   'Shiann Darkangelo',
   'Stephanie Markowski',
   'Taylor House',
   'Tereza Vanišová',
   'Victoria Bach',
   'Zoe Boyd'},
  'Toronto': {'Allie Munroe',
   'Anna Kjellbin',
   'Anneke Rankila',
   'Blayre Turnbull',
   'Carly Jackson',
   'Daryl Watts',
   'Emma Maltais',
   'Emma Woods',
   'Hannah Miller',
   'Hayley Scamurra',
   'Izzy Daniel',
   'Jesse Compher',
   'Jessica Kondas',
   'Jocelyne Larocque',
   'Julia Gosling',
   'Kaitlin Willoughby',
   'Kali Flanagan',
   'Kassidy Sauvé',
   'Kristen Campbell',
   'Laura Kluge',
   'Lauren Bernard',
   'Maggie Connors',
   'Megan Carter',
   'Natalie Spooner',
   'Noemi Neubauerová',
   'Olivia Knowles',
   'Raygan Kirk',
   'Renata Fast',
   'Rylind MacKinnon',
   'Samantha Cogan',
   'Sarah Nurse',
   'Savannah Harmon',
   'Victoria Bach'}},
 '2025-2026': {'Boston': {'Abbey Levy',
   'Abby Newhook',
   'Aerin Frankel',
   'Alina Müller',
   'Amanda Thiele',
   'Daniela Pejšová',
   'Ella Huber',
   'Hadley Hartmetz',
   'Haley Winn',
   'Hannah Brandt',
   'Jamie Lee Rattray',
   'Jessie Eldridge',
   'Jill Saulnier',
   'Laura Kluge',
   'Liz Schepers',
   'Loren Gabel',
   'Megan Keller',
   'Mia Biotti',
   'Noemi Neubauerová',
   'Olivia Mobley',
   'Olivia Zafuto',
   'Riley Brengman',
   'Rylind MacKinnon',
   'Shay Maloney',
   'Sophie Shirley',
   'Susanna Tapani',
   'Zoe Boyd'},
  'Minnesota': {'Abby Hustler',
   'Ava Rinker',
   'Britta Curl-Salemme',
   'Brooke Becker',
   'Claire Butorac',
   'Dominique Petrie',
   'Grace Zumwinkle',
   'Jincy Roese',
   "Kaitlyn O'Donohoe",
   'Katy Knoll',
   'Kelly Pannek',
   'Kendall Cooper',
   'Kendall Coyne Schofield',
   'Klára Hymlárová',
   'Lee Stecklein',
   'Maddie Rooney',
   'Madison Bizal',
   'Mae Batherson',
   'Marlène Boissonnault',
   'Natalie Buchbinder',
   'Nicole Hensley',
   'Peyton Anderson',
   'Samantha Cogan',
   'Sidney Morin',
   'Taylor Heise',
   'Vanessa Upson',
   'Élizabeth Giguère'},
  'Montréal': {'Abby Roque',
   'Alexandra Labelle',
   'Amanda Boulier',
   'Ann-Renée Desbiens',
   'Catherine Dubois',
   'Claire Vekich',
   'Dara Greig',
   'Erin Ambrose',
   'Hayley Scamurra',
   'Jade Downie-Landry',
   'Jessica DiGirolamo',
   'Kaitlin Willoughby',
   'Kati Tabin',
   'Kelly Ann Nadeau',
   'Laura Stacey',
   'Lina Ljungblom',
   'Maggie Flaherty',
   'Marie-Philip Poulin',
   'Maureen Murphy',
   'Maya Labad',
   'Megan Warrener',
   'Nadia Mattivi',
   'Natálie Mlýnková',
   'Nicole Gosling',
   'Samantha Isbell',
   'Sandra Abstreiter',
   'Shiann Darkangelo',
   'Skylar Irving',
   'Tamara Giaquinto'},
  'New York': {'Allyson Simpson',
   'Anna Bargman',
   'Anne Cherkowski',
   'Callie Shanahan',
   "Casey O'Brien",
   'Clair DeGeorge',
   'Dayle Ross',
   'Denisa Křížová',
   'Elle Hartje',
   'Emmy Fecteau',
   'Jaime Bourbonnais',
   'Kaley Doyle',
   'Kayla Vespa',
   'Kayle Osborne',
   'Kira Juodikis',
   "Kristin O'Neill",
   'Kristýna Kaltounková',
   'Lauren Bernard',
   'Maddi Wheeler',
   'Maja Nylén Persson',
   'Micah Zandee-Hart',
   'Nicole Vallario',
   'Olivia Knowles',
   'Paetyn Levis',
   'Sarah Bujold',
   'Sarah Fillier',
   'Savannah Norcross',
   'Taylor Girard'},
  'Ottawa': {'Alexa Vasko',
   'Alexie Guay',
   'Brianne Jenner',
   'Brooke Hobson',
   'Brooke McQuigge',
   'Emily Clark',
   'Emma Greco',
   'Fanuza Kadirova',
   'Gabbie Hughes',
   'Gwyneth Philips',
   'Jocelyne Larocque',
   'Kaitlyn Ross',
   'Kateřina Mrázová',
   'Kathryn Reilly',
   'Kendra Woodland',
   'Maggy Burbidge',
   'Michela Cava',
   'Olivia Wallin',
   'Peyton Hemp',
   'Rebecca Leslie',
   'Reece Hunt',
   'Ronja Savolainen',
   'Rory Guilday',
   'Sanni Ahola',
   'Sarah Wozniewicz',
   'Stephanie Markowski',
   'Taylor House',
   'Vita Poniatovskaia'},
  'Seattle': {'Alex Carpenter',
   'Aneta Tejralová',
   'Anna Wilgren',
   'Brooke Bryant',
   'Carly Jackson',
   'Cayla Barnes',
   'Corinne Schroeder',
   'Danielle Serdachny',
   'Emily Brown',
   'Emily Zumwinkle',
   'Gabrielle David',
   'Hannah Bilka',
   'Hannah Murphy',
   'Jada Habisch',
   'Jenna Buglioni',
   'Julia Gosling',
   'Lexie Adzija',
   'Lily Delianedis',
   'Lyndie Lobdell',
   'Marah Wagner',
   'Mariah Keopple',
   'Megan Carter',
   'Mikyla Grant-Mentis',
   'Natalie Snodgrass',
   'Sydney Langseth',
   'Theresa Schafzahl'},
  'Toronto': {'Allie Munroe',
   'Anna Kjellbin',
   'Anneke Rankila',
   'Blayre Turnbull',
   'Claire Dalton',
   'Clara Van Wieren',
   'Daryl Watts',
   'Elaine Chuli',
   'Ella Shelton',
   'Emma Gentry',
   'Emma Maltais',
   'Emma Woods',
   'Hanna Baskin',
   'Jesse Compher',
   'Jessica Kondas',
   'Jessie McPherson',
   'Kali Flanagan',
   'Kiara Zanon',
   'Kristin Della Rovere',
   'Lauren Messier',
   'Maggie Connors',
   'Natalie Spooner',
   'Raygan Kirk',
   'Renata Fast',
   'Sara Hjalmarsson',
   'Savannah Harmon'},
  'Vancouver': {'Abby Boreen',
   'Anna Meixner',
   'Anna Segedi',
   'Anna Shokhina',
   'Ashton Bell',
   'Brianna Brooks',
   'Claire Thompson',
   'Darcie Lappan',
   'Emerance Maschmeyer',
   'Gabby Rosenthal',
   'Hannah Miller',
   'Izzy Daniel',
   'Jenn Gardiner',
   'Katie Chan',
   'Kimberly Newell',
   'Kristen Campbell',
   'Madison Samoskevich',
   'Malia Schneider',
   'Mannon McMahon',
   'Mellissa Channell-Watkins',
   'Michelle Karvinen',
   'Nina Jobst-Smith',
   'Sarah Nurse',
   'Sini Karjalainen',
   'Sophie Jaques',
   'Sydney Bard',
   'Tereza Vanišová'}},
 '2026-2027': {'Boston': {'Aerin Frankel',
   'Amanda Boulier',
   'Amanda Thiele',
   'Ella Huber',
   'Grace Dwyer',
   'Haley Winn',
   'Jill Saulnier',
   'Laura Kluge',
   'Leah Stecker',
   'Liz Schepers',
   'Loren Gabel',
   'Megan Keller',
   'Olivia Mobley',
   'Rylind MacKinnon',
   'Shay Maloney',
   'Sophie Shirley',
   'Susanna Tapani',
   'Taylor House'},
  'Minnesota': {'Brooke Becker',
   'Claire Butorac',
   'Dominique Petrie',
   'Grace Zumwinkle',
   'Kelly Pannek',
   'Klára Hymlárová',
   'Lara Beecher',
   'Lee Stecklein',
   'Maddie Rooney',
   'Marlène Boissonnault',
   'Natalie Buchbinder',
   'Peyton Anderson',
   'Samantha Cogan',
   'Sara Swiderski',
   'Sidney Morin',
   'Taylor Heise',
   'Viivi Vainikka',
   'Élizabeth Giguère'},
  'Montréal': {'Abby Roque',
   'Alexandra Labelle',
   'Ann-Renée Desbiens',
   'Avi Adam',
   'Catherine Dubois',
   'Emma Maltais',
   'Jade Downie-Landry',
   'Jessica DiGirolamo',
   'Jessie Eldridge',
   'Kaitlin Willoughby',
   'Kati Tabin',
   'Laura Stacey',
   'Lina Ljungblom',
   'Maggie Flaherty',
   'Marie-Philip Poulin',
   'Megan Warrener',
   'Nadia Mattivi',
   'Petra Nieminen',
   'Tamara Giaquinto'},
  'New York': {'Anna Bargman',
   'Callie Shanahan',
   'Clair DeGeorge',
   'Dayle Ross',
   'Denisa Křížová',
   'Elaine Chuli',
   'Elisa Holopainen',
   'Elle Hartje',
   'Emma Peschel',
   'Emmy Fecteau',
   'Jaime Bourbonnais',
   'Kaley Doyle',
   'Kristýna Kaltounková',
   'Lauren Bernard',
   'Maja Nylén Persson',
   'Micah Zandee-Hart',
   'Nicole Vallario',
   'Paetyn Levis',
   'Sarah Fillier'},
  'Ottawa': {'Brooke Hobson',
   'Brooke McQuigge',
   'Dara Greig',
   'Emma Greco',
   'Fanuza Kadirova',
   'Gabbie Hughes',
   'Gwyneth Philips',
   'Jenna Buglioni',
   'Jocelyne Larocque',
   'Jordan Ray',
   'Kateřina Mrázová',
   'Kathryn Reilly',
   'Kendra Woodland',
   'Michela Cava',
   'Rebecca Leslie',
   'Ronja Savolainen',
   'Sanni Ahola',
   'Vita Poniatovskaia',
   'Vivian Jungels'},
  'Detroit': {'Alice Philbert',
   'Britta Curl-Salemme',
   'Casey Borgiel',
   'Cayla Barnes',
   'Daryl Watts',
   'Hannah Bilka',
   'Hilary Knight',
   'Jesse Compher',
   'Mellissa Channell-Watkins',
   'Mia Biotti',
   'Nina Jobst-Smith',
   'Olivia Wallin',
   'Shiann Darkangelo',
   'Stephanie Markowski',
   'Sydney Bard',
   'Taylor Girard'},
  'Hamilton': {'Abby Hustler',
   'Alexa Vasko',
   'Alina Müller',
   'Allyson Simpson',
   'Anna Kjellbin',
   'Brianne Jenner',
   'Emily Clark',
   'Jade Iginla',
   'Kayla Vespa',
   'Kayle Osborne',
   'Nelli Laitinen',
   'Nicole Gosling',
   'Peyton Hemp',
   'Riley Brengman',
   'Zoe Boyd'},
  'Las Vegas': {'Darcie Lappan',
   'Erin Ambrose',
   'Hayley Scamurra',
   'Jada Habisch',
   'Katy Knoll',
   'Kendall Cooper',
   'Lacey Eden',
   'Madison Bizal',
   'Mae Batherson',
   'Maureen Murphy',
   'Megan Carter',
   'Natalie Snodgrass',
   'Nicole Hensley',
   'Sydney Langseth',
   'Tessa Janecke'},
  'San Jose': {'Abbey Levy',
   'Anne Cherkowski',
   'Brooke Bryant',
   'Corinne Schroeder',
   'Daniela Pejšová',
   'Hadley Hartmetz',
   'Kristin Della Rovere',
   "Kristin O'Neill",
   'Laila Edwards',
   'Maddi Wheeler',
   'Maggie Connors',
   'Mariah Keopple',
   'Natálie Mlýnková',
   'Rory Guilday',
   'Sloane Matthews',
   'Tia Chan'},
  'Seattle': {'Abbey Murphy',
   'Alex Carpenter',
   'Aneta Tejralová',
   'Anna Wilgren',
   'Carly Jackson',
   'Danielle Serdachny',
   'Emerson Jarvis',
   'Emily Brown',
   'Emma Nuutinen',
   'Gabrielle David',
   'Hannah Murphy',
   'Julia Gosling',
   'Lexie Adzija',
   'Lily Delianedis',
   'Lyndie Lobdell',
   'Mikyla Grant-Mentis',
   'Noemi Neubauerová',
   'Sydney Morrow',
   'Theresa Schafzahl'},
  'Toronto': {'Allie Munroe',
   'Claire Dalton',
   'Ella Shelton',
   'Emma Gentry',
   'Emma Woods',
   'Grace Campbell',
   'Jamie Lee Rattray',
   'Jamie Nelson',
   'Jessica Kondas',
   'Jessie McPherson',
   'Kali Flanagan',
   'Kirsten Simms',
   'Lauren Messier',
   'Natalie Spooner',
   'Raygan Kirk',
   'Renata Fast'},
  'Vancouver': {'Abby Boreen',
   'Anna Segedi',
   'Ashton Bell',
   'Dominika Lásková',
   'Emerance Maschmeyer',
   'Gabby Rosenthal',
   'Hannah Miller',
   'Izzy Daniel',
   'Jenn Gardiner',
   'Jules Constantinople',
   'KK Harvey',
   'Katie Chan',
   'Kristen Campbell',
   'Mannon McMahon',
   'Sarah Nurse',
   'Sophie Jaques',
   'Tereza Vanišová',
   'Thea Johansson'}}}

In [ ]:
player_id_map

{'Emily Brown': '2',
 'Megan Keller': '12',
 'Sidney Morin': '167',
 'Lexie Adzija': '49',
 'Sophie Shirley': '18',
 'Alina Müller': '15',
 'Taylor Wenczkowski': '111',
 'Kaleigh Fratkin': '7',
 'Caitrin Lonergan': '176',
 'Amanda Pelkey': '110',
 'Taylor Girard': '9',
 'Abby Cook': '117',
 'Sophie Jaques': '11',
 'Gigi Marvin': '109',
 'Hannah Brandt': '1',
 'Hilary Knight': '13',
 'Jessica DiGirolamo': '5',
 'Emma Buckles': '3',
 'Sammy Davis': '107',
 'Shiann Darkangelo': '4',
 'Emma Söderberg': '19',
 'Aerin Frankel': '6',
 'Cami Kronish': '113',
 'Loren Gabel': '8',
 'Theresa Schafzahl': '17',
 'Jamie Lee Rattray': '16',
 'Samantha Isbell': '108',
 'Nicole Kosta': '14',
 'Susanna Tapani': '78',
 'Jess Healey': '10',
 'Kelly Babstock': '175',
 'Lee Stecklein': '24',
 'Nikki Nightengale': '120',
 'Claire Butorac': '102',
 'Sydney Brodt': '92',
 'Sophia Kunin': '103',
 'Kelly Pannek': '23',
 'Grace Zumwinkle': '25',
 'Clair DeGeorge': '116',
 'Brooke Bryant': '91',
 'Brittyn Fleming': '105',
 'Maggie Flaherty': '79',
 'Liz Schepers': '97',
 'Natalie Buchbinder': '90',
 'Mellissa Channell-Watkins': '129',
 'Abby Boreen': '114',
 'Emma Greco': '118',
 'Kendall Coyne Schofield': '20',
 'Taylor Heise': '21',
 'Amanda Leveille': '122',
 'Nicole Hensley': '22',
 'Lauren Bench': '121',
 'Maddie Rooney': '123',
 'Dominique Kremer': '119',
 'Denisa Křížová': '104',
 'Michela Cava': '115',
 'Marlène Boissonnault': '166',
 'Mariah Keopple': '99',
 'Brooke Stacey': '177',
 'Catherine Daoust': '163',
 'Madison Bizal': '162',
 'Laura Stacey': '32',
 'Gabrielle David': '156',
 'Kati Tabin': '84',
 'Brigitte Laganière': '164',
 'Leah Lum': '159',
 'Jillian Dempsey': '27',
 'Maureen Murphy': '98',
 'Sarah Lefort': '158',
 'Alexandra Poznikoff': '160',
 'Mikyla Grant-Mentis': '138',
 'Elaine Chuli': '85',
 'Tereza Vanišová': '161',
 'Kennedy Marchment': '29',
 'Erin Ambrose': '83',
 'Ann-Sophie Bettez': '80',
 'Mélodie Daoust': '168',
 'Sarah Bujold': '81',
 'Catherine Dubois': '157',
 'Marie-Philip Poulin': '31',
 'Liliane Perreault': '139',
 'Ann-Renée Desbiens': '28',
 'Claire Dalton': '26',
 "Kristin O'Neill": '30',
 'Amanda Boulier': '51',
 'Dominika Lásková': '82',
 'Olivia Zafuto': '46',
 'Claire Thompson': '169',
 'Brooke Hobson': '38',
 'Jessie Eldridge': '36',
 'Kayla Vespa': '45',
 'Abby Roque': '42',
 'Alexandra Labelle': '39',
 'Jaime Bourbonnais': '87',
 'Alexa Gruschow': '146',
 'Ella Shelton': '44',
 'Élizabeth Giguère': '37',
 'Paetyn Levis': '40',
 'Madison Packer': '148',
 'Alex Carpenter': '34',
 'Jade Downie-Landry': '35',
 'Micah Zandee-Hart': '47',
 'Corinne Schroeder': '155',
 'Lindsey Post': '154',
 'Abbey Levy': '41',
 'Jill Saulnier': '149',
 'Johanna Fällman': '152',
 'Emma Woods': '86',
 'Savannah Norcross': '147',
 'Carley Olivier': '153',
 'Taylor Baker': '150',
 'Chloé Aurard-Bushee': '33',
 'Aneta Tejralová': '62',
 'Zoe Boyd': '52',
 'Natalie Snodgrass': '142',
 'Daryl Watts': '63',
 'Becca Gilmore': '55',
 'Akane Shiga': '141',
 'Hayley Scamurra': '61',
 'Savannah Harmon': '56',
 'Kateřina Mrázová': '88',
 'Gabbie Hughes': '57',
 'Malia Schneider': '140',
 'Brianne Jenner': '58',
 'Ashton Bell': '50',
 'Lauren MacInnis': '112',
 'Kristin Della Rovere': '54',
 'Emily Clark': '53',
 'Sandra Abstreiter': '48',
 'Rachel McQuigge': '145',
 'Emerance Maschmeyer': '59',
 'Jincy Roese': '60',
 'Rosalie Demers': '136',
 'Fanni Garát-Gasparics': '137',
 'Audrey-Ann Veilette': '178',
 'Victoria Howran': '144',
 'Taylor Davison': '143',
 'Jocelyne Larocque': '71',
 'Lauriane Rougeau': '133',
 'Kali Flanagan': '68',
 'Olivia Knowles': '131',
 'Alexa Vasko': '101',
 'Allie Munroe': '74',
 'Renata Fast': '67',
 'Samantha Cogan': '126',
 'Jesse Compher': '65',
 'Rebecca Leslie': '72',
 'Sarah Nurse': '75',
 'Emma Keenan': '130',
 'Maggie Connors': '66',
 'Jess Jones': '127',
 'Natalie Spooner': '100',
 'Emma Maltais': '73',
 'Kaitlin Willoughby': '128',
 'Hannah Miller': '89',
 'Erica Howe': '70',
 'Blayre Turnbull': '76',
 'Brittany Howard': '69',
 'Kristen Campbell': '64',
 'Victoria Bach': '125',
 'Jessica Kondas': '132',
 'Carly Jackson': '134',
 'Maude Poulin-Labelle': '165',
 'Hadley Hartmetz': '182',
 'Sydney Bard': '180',
 'Hannah Bilka': '181',
 'Shay Maloney': '183',
 'Klára Peslarová': '186',
 'Daniela Pejšová': '185',
 'Brooke McQuigge': '192',
 'Katy Knoll': '191',
 'Charlotte Akervik': '187',
 'Mae Batherson': '188',
 "Kaitlyn O'Donohoe": '194',
 'Dominique Petrie': '195',
 'Lucy Morgan': '193',
 'Klára Hymlárová': '190',
 'Britta Curl-Salemme': '189',
 'Cayla Barnes': '196',
 'Anna Wilgren': '203',
 'Jenn Gardiner': '198',
 'Dara Greig': '199',
 'Lina Ljungblom': '201',
 'Kelly Ann Nadeau': '202',
 'Anna Kjellbin': '200',
 'Tricia Deguire': '197',
 'Alexie Guay': '233',
 'Maja Nylén Persson': '229',
 'Sarah Fillier': '205',
 'Elle Hartje': '206',
 'Gabby Rosenthal': '227',
 'Lauren Bernard': '207',
 'Allyson Simpson': '230',
 'Emmy Fecteau': '204',
 'Kayle Osborne': '228',
 'Noora Tulus': '231',
 'Stephanie Markowski': '219',
 'Mannon McMahon': '220',
 'Taylor House': '217',
 'Gwyneth Philips': '222',
 'Ronja Savolainen': '223',
 'Danielle Serdachny': '224',
 'Anna Meixner': '221',
 'Jessica Adolfsson': '215',
 'Logan Angers': '216',
 'Raygan Kirk': '211',
 'Izzy Daniel': '209',
 'Anneke Rankila': '213',
 'Megan Carter': '208',
 'Laura Kluge': '212',
 'Kassidy Sauvé': '234',
 'Rylind MacKinnon': '232',
 'Noemi Neubauerová': '214',
 'Julia Gosling': '210',
 'Mia Biotti': '254',
 'Haley Winn': '246',
 'Olivia Mobley': '256',
 'Riley Brengman': '255',
 'Abby Newhook': '259',
 'Ella Huber': '243',
 'Amanda Thiele': '262',
 'Kendall Cooper': '236',
 'Brooke Becker': '264',
 'Ava Rinker': '267',
 'Vanessa Upson': '269',
 'Abby Hustler': '247',
 'Peyton Anderson': '263',
 'Megan Warrener': '270',
 'Maya Labad': '273',
 'Tamara Giaquinto': '271',
 'Claire Vekich': '276',
 'Nicole Gosling': '253',
 'Skylar Irving': '272',
 'Nadia Mattivi': '320',
 'Natálie Mlýnková': '274',
 'Dayle Ross': '251',
 'Nicole Vallario': '283',
 'Maddi Wheeler': '285',
 'Anna Bargman': '277',
 'Anne Cherkowski': '249',
 "Casey O'Brien": '280',
 'Callie Shanahan': '282',
 'Kaley Doyle': '278',
 'Kira Juodikis': '279',
 'Kristýna Kaltounková': '245',
 'Sanni Ahola': '238',
 'Rory Guilday': '242',
 'Kathryn Reilly': '289',
 'Vita Poniatovskaia': '288',
 'Olivia Wallin': '296',
 'Reece Hunt': '318',
 'Sarah Wozniewicz': '241',
 'Peyton Hemp': '286',
 'Kaitlyn Ross': '260',
 'Kendra Woodland': '290',
 'Fanuza Kadirova': '240',
 'Maggy Burbidge': '319',
 'Emily Zumwinkle': '298',
 'Lily Delianedis': '291',
 'Jenna Buglioni': '237',
 'Lyndie Lobdell': '294',
 'Jada Habisch': '292',
 'Marah Wagner': '295',
 'Sydney Langseth': '293',
 'Hannah Murphy': '250',
 'Hanna Baskin': '311',
 'Kiara Zanon': '317',
 'Lauren Messier': '315',
 'Sara Hjalmarsson': '313',
 'Emma Gentry': '244',
 'Clara Van Wieren': '316',
 'Jessie McPherson': '314',
 'Sini Karjalainen': '321',
 'Madison Samoskevich': '310',
 'Katie Chan': '301',
 'Nina Jobst-Smith': '305',
 'Michelle Karvinen': '252',
 'Kimberly Newell': '309',
 'Anna Segedi': '248',
 'Darcie Lappan': '306',
 'Anna Shokhina': '239',
 'Brianna Brooks': '300',
 'Grace Dwyer': '336',
 'Leah Stecker': '352',
 'Lara Beecher': '326',
 'Sara Swiderski': '335',
 'Viivi Vainikka': '346',
 'Avi Adam': '349',
 'Petra Nieminen': '338',
 'Elisa Holopainen': '344',
 'Emma Peschel': '333',
 'Vivian Jungels': '337',
 'Jordan Ray': '348',
 'Casey Borgiel': '347',
 'Alice Philbert': '323',
 'Jade Iginla': '343',
 'Nelli Laitinen': '332',
 'Lacey Eden': '331',
 'Tessa Janecke': '329',
 'Tia Chan': '353',
 'Laila Edwards': '330',
 'Sloane Matthews': '341',
 'Emerson Jarvis': '351',
 'Sydney Morrow': '340',
 'Abbey Murphy': '328',
 'Emma Nuutinen': '324',
 'Grace Campbell': '325',
 'Jamie Nelson': '345',
 'Kirsten Simms': '334',
 'Jules Constantinople': '350',
 'KK Harvey': '327',
 'Thea Johansson': '342'}

In [ ]:
# Add Hilary Knight to the Torrent 2025-2026 cuz she's not there for some reason
all_team_rosters["2025-2026"]["Seattle"].add("Hilary Knight")

In [ ]:
all_players = set()

for season_name, teams_rosters in all_team_rosters.items():
    for team_name, roster in teams_rosters.items():
          all_players.update(roster)

print(f"Total unique players: {len(all_players)}")
print(list(all_players)[:10]) # Display first 10 players to verify

Total unique players: 312
['Maude Poulin-Labelle', 'Carley Olivier', 'Erica Howe', 'Jamie Lee Rattray', 'Sophie Shirley', 'Noemi Neubauerová', 'Jaime Bourbonnais', 'Anna Meixner', 'Catherine Dubois', 'Élizabeth Giguère']

# Player source target dicts (without stats)
Given two seasons, create a player_source_target_dict which maps a player to their source-target transition in between seasons
```
{'Amanda Pelkey': ('Boston 2024', 'Boston 2024-2025'),
 'Jessica DiGirolamo': ('Boston 2024', 'Boston 2024-2025'),
 'Susanna Tapani': ('Minnesota 2024', 'Boston 2024-2025'),
 'Emily Brown': ('Boston 2024', 'Boston 2024-2025'),
 ```

player_source_target_dicts_list is a list of the player_source_target_dicts with sources 2024, 2024-2025, and 2025-2026.
```
 player_source_target_dicts_list = [player_source_target_2024, player_source_target_2025, player_source_target_2026]
 ```

In [ ]:
def generate_source_target_player_dict(begin_season, end_season):
  begin_rosters = all_team_rosters[begin_season]
  end_rosters = all_team_rosters[end_season]

  player_source_target_dict = {}

  for begin_team in begin_rosters.keys():
    begin_team_roster = begin_rosters[begin_team]
    for player in begin_team_roster:
      for end_team in end_rosters.keys():
        end_team_roster = end_rosters[end_team]
        if player in end_team_roster:
          source_target = (begin_team +" "+ begin_season, end_team +" "+ end_season)
          player_source_target_dict[player]=source_target

  return player_source_target_dict

In [ ]:
player_source_target_2024 = generate_source_target_player_dict("2024", "2024-2025")
player_source_target_2025 = generate_source_target_player_dict("2024-2025", "2025-2026")
player_source_target_2026 = generate_source_target_player_dict("2025-2026", "2026-2027")

In [ ]:
list(player_source_target_2024.items())[:5]

[('Amanda Pelkey', ('Boston 2024', 'Boston 2024-2025')),
 ('Jessica DiGirolamo', ('Boston 2024', 'Boston 2024-2025')),
 ('Susanna Tapani', ('Minnesota 2024', 'Boston 2024-2025')),
 ('Emily Brown', ('Boston 2024', 'Boston 2024-2025')),
 ('Jamie Lee Rattray', ('Boston 2024', 'Boston 2024-2025'))]

In [ ]:
player_source_target_dicts_list = [player_source_target_2024, player_source_target_2025, player_source_target_2026]

# Functions to fetch player stats

Create `player_season_stats_map` which will map a player to a dict which maps the season id to number of goals scored.

```
{'Emily Brown': {'8': '0', '5': '1', '1': '1'},
 'Megan Keller': {'8': '7', '5': '5', '1': '4'},
 'Sidney Morin': {'8': '0', '5': '3', '1': '1'},
 'Lexie Adzija': {'8': '4', '5': '2', '1': '1'},
 ...
 ```

In [ ]:
def get_goals_for_player_by_season(player_name):
  player_id = player_id_map[player_name]

  player_stats_response = requests.get("https://lscluster.hockeytech.com/feed/index.php?feed=modulekit&view=player&category=seasonstats&player_id="+player_id+"&key=446521baf8c38984&client_code=pwhl")
  if player_stats_response.status_code != 200:
    return None

  season_stats_dict = {}

  player_stats_json = player_stats_response.json()
  all_season_stats = player_stats_json["SiteKit"]["Player"]
  if isinstance(all_season_stats, bool):
    # print(player_name)
    return None

  regular_season_stats = all_season_stats.get("regular")
  if regular_season_stats is None:
    print(player_name)
    return None

  for season_stats in regular_season_stats:
    if season_stats["season_name"] != "Total":
      season_stats_dict[season_stats["season_id"]] = season_stats["goals"]

  return season_stats_dict

In [ ]:
player_id_map["Hilary Knight"]

'13'

In [ ]:
hk_stats = get_goals_for_player_by_season("Hilary Knight")

In [ ]:
hk_stats

{'8': '5', '5': '15', '1': '6'}

In [ ]:
player_season_stats_map = {}
for player_name in player_id_map.keys():
  player_season_stats_map[player_name] = get_goals_for_player_by_season(player_name)

Cami Kronish
Nikki Nightengale
Amanda Leveille
Lauren Bench
Liliane Perreault
Lauren MacInnis
Rachel McQuigge
Taylor Davison
Emma Keenan
Tricia Deguire
Logan Angers
Ava Rinker
Megan Warrener
Claire Vekich
Kaley Doyle
Kimberly Newell

In [ ]:
player_season_stats_map

{'Emily Brown': {'8': '0', '5': '1', '1': '1'},
 'Megan Keller': {'8': '7', '5': '5', '1': '4'},
 'Sidney Morin': {'8': '0', '5': '3', '1': '1'},
 'Lexie Adzija': {'8': '4', '5': '2', '1': '1'},
 'Sophie Shirley': {'8': '3', '5': '0', '1': '3'},
 'Alina Müller': {'8': '4', '5': '7', '1': '5'},
 'Taylor Wenczkowski': {'1': '0'},
 'Kaleigh Fratkin': {'1': '2'},
 'Caitrin Lonergan': None,
 'Amanda Pelkey': {'5': '3', '1': '1'},
 'Taylor Girard': {'8': '7', '5': '1', '1': '4'},
 'Abby Cook': {'1': '1'},
 'Sophie Jaques': {'8': '9', '5': '7', '1': '2'},
 'Gigi Marvin': {'1': '1'},
 'Hannah Brandt': {'8': '0', '5': '3', '1': '5'},
 'Hilary Knight': {'8': '5', '5': '15', '1': '6'},
 'Jessica DiGirolamo': {'8': '1', '5': '1', '1': '0'},
 'Emma Buckles': {'1': '0'},
 'Sammy Davis': {'1': '0'},
 'Shiann Darkangelo': {'8': '4', '5': '8', '1': '0'},
 'Emma Söderberg': {'5': '0', '1': '0'},
 'Aerin Frankel': {'8': '0', '5': '0', '1': '0'},
 'Cami Kronish': None,
 'Loren Gabel': {'8': '1', '5': '2', '1': '4'},
 'Theresa Schafzahl': {'8': '2', '5': '3', '1': '3'},
 'Jamie Lee Rattray': {'8': '4', '5': '4', '1': '3'},
 'Samantha Isbell': {'8': '0', '5': '0', '1': '0'},
 'Nicole Kosta': {'1': '1'},
 'Susanna Tapani': {'8': '9', '5': '11', '1': '2'},
 'Jess Healey': {'1': '1'},
 'Kelly Babstock': {'5': '0', '1': '0'},
 'Lee Stecklein': {'8': '1', '5': '3', '1': '2'},
 'Nikki Nightengale': None,
 'Claire Butorac': {'8': '0', '5': '2', '1': '1'},
 'Sydney Brodt': {'1': '0'},
 'Sophia Kunin': {'1': '2'},
 'Kelly Pannek': {'8': '16', '5': '3', '1': '4'},
 'Grace Zumwinkle': {'8': '13', '5': '4', '1': '11'},
 'Clair DeGeorge': {'8': '0', '5': '0', '1': '0'},
 'Brooke Bryant': {'8': '0', '5': '1', '1': '1'},
 'Brittyn Fleming': {'1': '1'},
 'Maggie Flaherty': {'8': '4', '5': '1', '1': '1'},
 'Liz Schepers': {'8': '5', '5': '2', '1': '0'},
 'Natalie Buchbinder': {'8': '1', '5': '0', '1': '2'},
 'Mellissa Channell-Watkins': {'8': '0', '5': '1', '1': '0'},
 'Abby Boreen': {'8': '4', '5': '6', '1': '4'},
 'Emma Greco': {'8': '0', '5': '0', '1': '0'},
 'Kendall Coyne Schofield': {'8': '12', '5': '12', '1': '6'},
 'Taylor Heise': {'8': '13', '5': '8', '1': '4'},
 'Amanda Leveille': None,
 'Nicole Hensley': {'8': '0', '5': '0', '1': '0'},
 'Lauren Bench': None,
 'Maddie Rooney': {'8': '0', '5': '0', '1': '0'},
 'Dominique Kremer': {'1': '0'},
 'Denisa Křížová': {'8': '1', '5': '4', '1': '3'},
 'Michela Cava': {'8': '0', '5': '9', '1': '5'},
 'Marlène Boissonnault': {'8': '0'},
 'Mariah Keopple': {'8': '0', '5': '3', '1': '0'},
 'Brooke Stacey': None,
 'Catherine Daoust': {'5': '0', '1': '1'},
 'Madison Bizal': {'8': '0', '1': '0'},
 'Laura Stacey': {'8': '7', '5': '11', '1': '10'},
 'Gabrielle David': {'8': '1', '5': '0', '1': '2'},
 'Kati Tabin': {'8': '2', '5': '4', '1': '1'},
 'Brigitte Laganière': {'1': '0'},
 'Leah Lum': {'1': '1'},
 'Jillian Dempsey': {'5': '0', '1': '1'},
 'Maureen Murphy': {'8': '4', '5': '3', '1': '5'},
 'Sarah Lefort': {'1': '1'},
 'Alexandra Poznikoff': {'1': '0'},
 'Mikyla Grant-Mentis': {'8': '3', '5': '3', '1': '2'},
 'Elaine Chuli': {'8': '0', '5': '0', '1': '0'},
 'Tereza Vanišová': {'8': '4', '5': '15', '1': '0'},
 'Kennedy Marchment': {'1': '1'},
 'Erin Ambrose': {'8': '0', '5': '0', '1': '4'},
 'Ann-Sophie Bettez': {'1': '2'},
 'Mélodie Daoust': {'1': '3'},
 'Sarah Bujold': {'1': '3'},
 'Catherine Dubois': {'8': '4', '5': '6', '1': '2'},
 'Marie-Philip Poulin': {'8': '9', '5': '19', '1': '10'},
 'Liliane Perreault': None,
 'Ann-Renée Desbiens': {'8': '0', '5': '0', '1': '0'},
 'Claire Dalton': {'8': '1', '5': '3', '1': '5'},
 "Kristin O'Neill": {'8': '4', '5': '1', '1': '4'},
 'Amanda Boulier': {'8': '0', '5': '1', '1': '0'},
 'Dominika Lásková': {'5': '0', '1': '0'},
 'Olivia Zafuto': {'8': '0', '1': '0'},
 'Claire Thompson': {'8': '4', '5': '4'},
 'Brooke Hobson': {'8': '1', '5': '1', '1': '1'},
 'Jessie Eldridge': {'8': '7', '5': '9', '1': '7'},
 'Kayla Vespa': {'8': '0', '5': '0', '1': '2'},
 'Abby Roque': {'8': '8', '5': '6', '1': '6'},
 'Alexandra Labelle': {'8': '0', '5': '1', '1': '1'},
 'Jaime Bourbonnais': {'8': '1', '5': '2', '1': '5'},
 'Alexa Gruschow': {'1': '0'},
 'Ella Shelton': {'8': '3', '5': '8', '1': '7'},
 'Élizabeth Giguère': {'8': '0', '5': '2', '1': '3'},
 'Paetyn Levis': {'8': '5', '5': '4', '1': '0'},
 'Madison Packer': {'1': '0'},
 'Alex Carpenter': {'8': '12', '5': '11', '1': '8'},
 'Jade Downie-Landry': {'8': '2', '5': '4', '1': '8'},
 'Micah Zandee-Hart': {'8': '1', '5': '1', '1': '0'},
 'Corinne Schroeder': {'8': '0', '5': '0', '1': '0'},
 'Lindsey Post': {'1': '0'},
 'Abbey Levy': {'8': '0', '5': '0', '1': '0'},
 'Jill Saulnier': {'8': '2', '5': '2', '1': '1'},
 'Johanna Fällman': {'1': '0'},
 'Emma Woods': {'8': '1', '5': '3', '1': '2'},
 'Savannah Norcross': {'8': '1', '1': '0'},
 'Carley Olivier': {'1': '0'},
 'Taylor Baker': {'5': '0', '1': '0'},
 'Chloé Aurard-Bushee': {'5': '2', '1': '1'},
 'Aneta Tejralová': {'8': '2', '5': '1', '1': '2'},
 'Zoe Boyd': {'8': '0', '5': '0', '1': '0'},
 'Natalie Snodgrass': {'8': '2', '5': '1', '1': '1'},
 'Daryl Watts': {'8': '10', '5': '12', '1': '10'},
 'Becca Gilmore': {'1': '0'},
 'Akane Shiga': {'1': '2'},
 'Hayley Scamurra': {'8': '8', '5': '1', '1': '5'},
 'Savannah Harmon': {'8': '2', '5': '0', '1': '3'},
 'Kateřina Mrázová': {'8': '2', '5': '3', '1': '6'},
 'Gabbie Hughes': {'8': '5', '5': '5', '1': '9'},
 'Malia Schneider': {'8': '0', '1': '0'},
 'Brianne Jenner': {'8': '12', '5': '7', '1': '9'},
 'Ashton Bell': {'8': '2', '5': '3', '1': '2'},
 'Lauren MacInnis': None,
 'Kristin Della Rovere': {'8': '0', '1': '1'},
 'Emily Clark': {'8': '3', '5': '9', '1': '4'},
 'Sandra Abstreiter': {'8': '0', '1': '0'},
 'Rachel McQuigge': None,
 'Emerance Maschmeyer': {'8': '0', '5': '0', '1': '0'},
 'Jincy Roese': {'8': '0', '5': '3', '1': '0'},
 'Rosalie Demers': {'1': '0'},
 'Fanni Garát-Gasparics': {'1': '1'},
 'Audrey-Ann Veilette': None,
 'Victoria Howran': {'1': '0'},
 'Taylor Davison': None,
 'Jocelyne Larocque': {'8': '1', '5': '0', '1': '1'},
 'Lauriane Rougeau': {'1': '0'},
 'Kali Flanagan': {'8': '2', '5': '3', '1': '3'},
 'Olivia Knowles': {'8': '0', '5': '0', '1': '0'},
 'Alexa Vasko': {'8': '2', '5': '2', '1': '2'},
 'Allie Munroe': {'8': '0', '5': '1', '1': '1'},
 'Renata Fast': {'8': '1', '5': '6', '1': '3'},
 'Samantha Cogan': {'8': '0', '1': '2'},
 'Jesse Compher': {'8': '6', '5': '9', '1': '1'},
 'Rebecca Leslie': {'8': '14', '5': '1', '1': '2'},
 'Sarah Nurse': {'8': '9', '5': '6', '1': '11'},
 'Emma Keenan': None,
 'Maggie Connors': {'8': '3', '5': '2', '1': '3'},
 'Jess Jones': {'1': '0'},
 'Natalie Spooner': {'8': '3', '5': '3', '1': '20'},
 'Emma Maltais': {'8': '3', '5': '4', '1': '4'},
 'Kaitlin Willoughby': {'8': '3', '5': '0', '1': '0'},
 'Hannah Miller': {'8': '7', '5': '10', '1': '7'},
 'Erica Howe': {'1': '0'},
 'Blayre Turnbull': {'8': '9', '5': '5', '1': '3'},
 'Brittany Howard': {'1': '2'},
 'Kristen Campbell': {'8': '0', '5': '0', '1': '0'},
 'Victoria Bach': {'5': '2', '1': '2'},
 'Jessica Kondas': {'8': '0', '5': '1'},
 'Carly Jackson': {'8': '0', '5': '0'},
 'Maude Poulin-Labelle': {'1': '0'},
 'Hadley Hartmetz': {'8': '0', '5': '0'},
 'Sydney Bard': {'8': '0', '5': '1'},
 'Hannah Bilka': {'8': '4', '5': '5'},
 'Shay Maloney': {'8': '3', '5': '3'},
 'Klára Peslarová': {'5': '0'},
 'Daniela Pejšová': {'8': '2', '5': '0'},
 'Brooke McQuigge': {'8': '0', '5': '8'},
 'Katy Knoll': {'8': '7', '5': '1'},
 'Charlotte Akervik': {'5': '0'},
 'Mae Batherson': {'8': '3', '5': '0'},
 "Kaitlyn O'Donohoe": {'8': '1', '5': '0'},
 'Dominique Petrie': {'8': '2', '5': '3'},
 'Lucy Morgan': {'5': '0'},
 'Klára Hymlárová': {'8': '3', '5': '1'},
 'Britta Curl-Salemme': {'8': '11', '5': '9'},
 'Cayla Barnes': {'8': '3', '5': '2'},
 'Anna Wilgren': {'8': '3', '5': '3'},
 'Jenn Gardiner': {'8': '9', '5': '5'},
 'Dara Greig': {'8': '3', '5': '0'},
 'Lina Ljungblom': {'8': '4', '5': '3'},
 'Kelly Ann Nadeau': {'8': '0', '5': '0'},
 'Anna Kjellbin': {'8': '1', '5': '0'},
 'Tricia Deguire': None,
 'Alexie Guay': None,
 'Maja Nylén Persson': {'8': '2', '5': '2'},
 'Sarah Fillier': {'8': '9', '5': '13'},
 'Elle Hartje': {'8': '0', '5': '0'},
 'Gabby Rosenthal': {'8': '1', '5': '1'},
 'Lauren Bernard': {'8': '0', '5': '0'},
 'Allyson Simpson': {'8': '3', '5': '1'},
 'Emmy Fecteau': {'8': '0', '5': '1'},
 'Kayle Osborne': {'8': '0', '5': '0'},
 'Noora Tulus': {'5': '1'},
 'Stephanie Markowski': {'8': '1', '5': '1'},
 'Mannon McMahon': {'8': '3', '5': '4'},
 'Taylor House': {'8': '0', '5': '1'},
 'Gwyneth Philips': {'8': '0', '5': '0'},
 'Ronja Savolainen': {'8': '4', '5': '2'},
 'Danielle Serdachny': {'8': '7', '5': '2'},
 'Anna Meixner': {'8': '1', '5': '1'},
 'Jessica Adolfsson': {'5': '0'},
 'Logan Angers': None,
 'Raygan Kirk': {'8': '0', '5': '0'},
 'Izzy Daniel': {'8': '7', '5': '2'},
 'Anneke Rankila': {'5': '0'},
 'Megan Carter': {'8': '1', '5': '0'},
 'Laura Kluge': {'8': '1', '5': '0'},
 'Kassidy Sauvé': None,
 'Rylind MacKinnon': {'8': '0', '5': '0'},
 'Noemi Neubauerová': {'8': '0', '5': '0'},
 'Julia Gosling': {'8': '6', '5': '4'},
 'Mia Biotti': {'8': '0'},
 'Haley Winn': {'8': '5'},
 'Olivia Mobley': {'8': '3'},
 'Riley Brengman': {'8': '2'},
 'Abby Newhook': {'8': '7'},
 'Ella Huber': {'8': '4'},
 'Amanda Thiele': {'8': '0'},
 'Kendall Cooper': {'8': '2'},
 'Brooke Becker': {'8': '0'},
 'Ava Rinker': None,
 'Vanessa Upson': {'8': '0'},
 'Abby Hustler': {'8': '4'},
 'Peyton Anderson': {'8': '1'},
 'Megan Warrener': None,
 'Maya Labad': {'8': '1'},
 'Tamara Giaquinto': {'8': '0'},
 'Claire Vekich': None,
 'Nicole Gosling': {'8': '3'},
 'Skylar Irving': {'8': '3'},
 'Nadia Mattivi': {'8': '0'},
 'Natálie Mlýnková': {'8': '5'},
 'Dayle Ross': {'8': '0'},
 'Nicole Vallario': {'8': '1'},
 'Maddi Wheeler': {'8': '3'},
 'Anna Bargman': {'8': '4'},
 'Anne Cherkowski': {'8': '2'},
 "Casey O'Brien": {'8': '7'},
 'Callie Shanahan': {'8': '0'},
 'Kaley Doyle': None,
 'Kira Juodikis': {'8': '0'},
 'Kristýna Kaltounková': {'8': '11'},
 'Sanni Ahola': {'8': '0'},
 'Rory Guilday': {'8': '1'},
 'Kathryn Reilly': {'8': '0'},
 'Vita Poniatovskaia': {'8': '0'},
 'Olivia Wallin': {'8': '0'},
 'Reece Hunt': None,
 'Sarah Wozniewicz': {'8': '7'},
 'Peyton Hemp': {'8': '2'},
 'Kaitlyn Ross': None,
 'Kendra Woodland': {'8': '0'},
 'Fanuza Kadirova': {'8': '10'},
 'Maggy Burbidge': None,
 'Emily Zumwinkle': {'8': '0'},
 'Lily Delianedis': {'8': '0'},
 'Jenna Buglioni': {'8': '0'},
 'Lyndie Lobdell': {'8': '0'},
 'Jada Habisch': {'8': '1'},
 'Marah Wagner': {'8': '0'},
 'Sydney Langseth': {'8': '0'},
 'Hannah Murphy': {'8': '0'},
 'Hanna Baskin': {'8': '0'},
 'Kiara Zanon': {'8': '1'},
 'Lauren Messier': {'8': '1'},
 'Sara Hjalmarsson': {'8': '3'},
 'Emma Gentry': {'8': '1'},
 'Clara Van Wieren': {'8': '0'},
 'Jessie McPherson': None,
 'Sini Karjalainen': {'8': '0'},
 'Madison Samoskevich': {'8': '1'},
 'Katie Chan': {'8': '1'},
 'Nina Jobst-Smith': {'8': '0'},
 'Michelle Karvinen': {'8': '3'},
 'Kimberly Newell': None,
 'Anna Segedi': {'8': '1'},
 'Darcie Lappan': {'8': '0'},
 'Anna Shokhina': {'8': '1'},
 'Brianna Brooks': {'8': '0'},
 'Grace Dwyer': None,
 'Leah Stecker': None,
 'Lara Beecher': None,
 'Sara Swiderski': None,
 'Viivi Vainikka': None,
 'Avi Adam': None,
 'Petra Nieminen': None,
 'Elisa Holopainen': None,
 'Emma Peschel': None,
 'Vivian Jungels': None,
 'Jordan Ray': None,
 'Casey Borgiel': None,
 'Alice Philbert': None,
 'Jade Iginla': None,
 'Nelli Laitinen': None,
 'Lacey Eden': None,
 'Tessa Janecke': None,
 'Tia Chan': None,
 'Laila Edwards': None,
 'Sloane Matthews': None,
 'Emerson Jarvis': None,
 'Sydney Morrow': None,
 'Abbey Murphy': None,
 'Emma Nuutinen': None,
 'Grace Campbell': None,
 'Jamie Nelson': None,
 'Kirsten Simms': None,
 'Jules Constantinople': None,
 'KK Harvey': None,
 'Thea Johansson': None}

# Generate source target player dict (with goals)

Each player will map to a tuple: `((source, target), goals scored in source season)`

```
{'Amanda Pelkey': (('Boston 2024', 'Boston 2024-2025'), '1'),
 'Jessica DiGirolamo': (('Boston 2024', 'Boston 2024-2025'), '0'),
 'Susanna Tapani': (('Minnesota 2024', 'Boston 2024-2025'), '2'),
 'Emily Brown': (('Boston 2024', 'Boston 2024-2025'), '1'),
 ...
 ```
Create `player_source_target_dicts_list_goals` which is a list of the player source target stats dicts for all seasons

```
 player_source_target_dicts_list_goals = [player_source_target_2024_goals, player_source_target_2025_goals, player_source_target_2026_goals]
 ```

 TODO: modify this to account for other stats

In [ ]:
def generate_source_target_player_dict_with_goals(begin_season, end_season):
  begin_rosters = all_team_rosters[begin_season]
  end_rosters = all_team_rosters[end_season]

  player_source_target_dict = {}

  for begin_team in begin_rosters.keys():
    begin_team_roster = begin_rosters[begin_team]
    for player in begin_team_roster:
      for end_team in end_rosters.keys():
        end_team_roster = end_rosters[end_team]
        if player in end_team_roster:
          source_target = (begin_team +" "+ begin_season, end_team +" "+ end_season)
          player_goals_map = player_season_stats_map[player]
          player_goals_for_season = 0
          if player_goals_map is not None:
            player_goals_result = player_goals_map.get(str(season_to_id_map[begin_season]))
            if player_goals_result is not None:
              player_goals_for_season = player_goals_result
          player_source_target_dict[player]=(source_target, player_goals_for_season)

  return player_source_target_dict

In [ ]:
player_source_target_2024_goals = generate_source_target_player_dict_with_goals("2024", "2024-2025")
player_source_target_2025_goals = generate_source_target_player_dict_with_goals("2024-2025", "2025-2026")
player_source_target_2026_goals = generate_source_target_player_dict_with_goals("2025-2026", "2026-2027")

In [ ]:
player_source_target_2024_goals

{'Amanda Pelkey': (('Boston 2024', 'Boston 2024-2025'), '1'),
 'Jessica DiGirolamo': (('Boston 2024', 'Boston 2024-2025'), '0'),
 'Susanna Tapani': (('Minnesota 2024', 'Boston 2024-2025'), '2'),
 'Emily Brown': (('Boston 2024', 'Boston 2024-2025'), '1'),
 'Jamie Lee Rattray': (('Boston 2024', 'Boston 2024-2025'), '3'),
 'Hannah Brandt': (('Boston 2024', 'Boston 2024-2025'), '5'),
 'Sophie Shirley': (('Boston 2024', 'Boston 2024-2025'), '3'),
 'Emma Söderberg': (('Boston 2024', 'Boston 2024-2025'), '0'),
 'Kelly Babstock': (('Boston 2024', 'Boston 2024-2025'), '0'),
 'Samantha Isbell': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Sidney Morin': (('Boston 2024', 'Boston 2024-2025'), '1'),
 'Megan Keller': (('Boston 2024', 'Boston 2024-2025'), '4'),
 'Sophie Jaques': (('Minnesota 2024', 'Minnesota 2024-2025'), '2'),
 'Theresa Schafzahl': (('Boston 2024', 'Boston 2024-2025'), '3'),
 'Shiann Darkangelo': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Lexie Adzija': (('Ottawa 2024', 'Boston 2024-2025'), '1'),
 'Alina Müller': (('Boston 2024', 'Boston 2024-2025'), '5'),
 'Aerin Frankel': (('Boston 2024', 'Boston 2024-2025'), '0'),
 'Taylor Girard': (('Boston 2024', 'New York 2024-2025'), '4'),
 'Loren Gabel': (('Boston 2024', 'Boston 2024-2025'), '4'),
 'Hilary Knight': (('Boston 2024', 'Boston 2024-2025'), '6'),
 'Taylor Heise': (('Minnesota 2024', 'Minnesota 2024-2025'), '4'),
 'Grace Zumwinkle': (('Minnesota 2024', 'Minnesota 2024-2025'), '11'),
 'Mellissa Channell-Watkins': (('Minnesota 2024', 'Minnesota 2024-2025'), '0'),
 'Maggie Flaherty': (('Minnesota 2024', 'Minnesota 2024-2025'), '1'),
 'Abby Boreen': (('Minnesota 2024', 'Montréal 2024-2025'), '4'),
 'Lee Stecklein': (('Minnesota 2024', 'Minnesota 2024-2025'), '2'),
 'Claire Butorac': (('Minnesota 2024', 'Minnesota 2024-2025'), '1'),
 'Michela Cava': (('Minnesota 2024', 'Minnesota 2024-2025'), '5'),
 'Liz Schepers': (('Minnesota 2024', 'Minnesota 2024-2025'), '0'),
 'Emma Greco': (('Minnesota 2024', 'Boston 2024-2025'), '0'),
 'Maddie Rooney': (('Minnesota 2024', 'Minnesota 2024-2025'), '0'),
 'Kendall Coyne Schofield': (('Minnesota 2024', 'Minnesota 2024-2025'), '6'),
 'Clair DeGeorge': (('Minnesota 2024', 'Montréal 2024-2025'), '0'),
 'Denisa Křížová': (('Minnesota 2024', 'Minnesota 2024-2025'), '3'),
 'Kelly Pannek': (('Minnesota 2024', 'Minnesota 2024-2025'), '4'),
 'Brooke Bryant': (('Minnesota 2024', 'Minnesota 2024-2025'), '1'),
 'Nicole Hensley': (('Minnesota 2024', 'Minnesota 2024-2025'), '0'),
 'Natalie Buchbinder': (('Minnesota 2024', 'Minnesota 2024-2025'), '2'),
 'Jillian Dempsey': (('Montréal 2024', 'Boston 2024-2025'), '1'),
 'Kennedy Marchment': (('Montréal 2024', 'Montréal 2024-2025'), '1'),
 'Laura Stacey': (('Montréal 2024', 'Montréal 2024-2025'), '10'),
 'Tereza Vanišová': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Marlène Boissonnault': (('Montréal 2024', 'Minnesota 2024-2025'), 0),
 'Maureen Murphy': (('Montréal 2024', 'Montréal 2024-2025'), '5'),
 'Catherine Dubois': (('Montréal 2024', 'Montréal 2024-2025'), '2'),
 'Mariah Keopple': (('Montréal 2024', 'Montréal 2024-2025'), '0'),
 'Ann-Renée Desbiens': (('Montréal 2024', 'Montréal 2024-2025'), '0'),
 'Amanda Boulier': (('Ottawa 2024', 'Montréal 2024-2025'), '0'),
 'Gabrielle David': (('Montréal 2024', 'Montréal 2024-2025'), '2'),
 'Claire Dalton': (('Montréal 2024', 'Montréal 2024-2025'), '5'),
 'Marie-Philip Poulin': (('Montréal 2024', 'Montréal 2024-2025'), '10'),
 'Kati Tabin': (('Montréal 2024', 'Montréal 2024-2025'), '1'),
 'Catherine Daoust': (('Montréal 2024', 'Montréal 2024-2025'), '1'),
 'Erin Ambrose': (('Montréal 2024', 'Montréal 2024-2025'), '4'),
 'Mikyla Grant-Mentis': (('Ottawa 2024', 'Montréal 2024-2025'), '2'),
 'Elaine Chuli': (('Montréal 2024', 'Montréal 2024-2025'), '0'),
 'Dominika Lásková': (('Montréal 2024', 'Montréal 2024-2025'), '0'),
 "Kristin O'Neill": (('Montréal 2024', 'Montréal 2024-2025'), '4'),
 'Chloé Aurard-Bushee': (('New York 2024', 'New York 2024-2025'), '1'),
 'Jessie Eldridge': (('New York 2024', 'New York 2024-2025'), '7'),
 'Abby Roque': (('New York 2024', 'New York 2024-2025'), '6'),
 'Olivia Zafuto': (('New York 2024', 'Boston 2024-2025'), '0'),
 'Micah Zandee-Hart': (('New York 2024', 'New York 2024-2025'), '0'),
 'Alex Carpenter': (('New York 2024', 'New York 2024-2025'), '8'),
 'Jaime Bourbonnais': (('New York 2024', 'New York 2024-2025'), '5'),
 'Élizabeth Giguère': (('New York 2024', 'New York 2024-2025'), '3'),
 'Abbey Levy': (('New York 2024', 'New York 2024-2025'), '0'),
 'Brooke Hobson': (('New York 2024', 'New York 2024-2025'), '1'),
 'Claire Thompson': (('New York 2024', 'Minnesota 2024-2025'), 0),
 'Jade Downie-Landry': (('New York 2024', 'New York 2024-2025'), '8'),
 'Taylor Baker': (('New York 2024', 'New York 2024-2025'), '0'),
 'Jill Saulnier': (('New York 2024', 'New York 2024-2025'), '1'),
 'Ella Shelton': (('New York 2024', 'New York 2024-2025'), '7'),
 'Emma Woods': (('New York 2024', 'Toronto 2024-2025'), '2'),
 'Corinne Schroeder': (('New York 2024', 'New York 2024-2025'), '0'),
 'Kayla Vespa': (('New York 2024', 'New York 2024-2025'), '2'),
 'Alexandra Labelle': (('New York 2024', 'Montréal 2024-2025'), '1'),
 'Paetyn Levis': (('New York 2024', 'New York 2024-2025'), '0'),
 'Emerance Maschmeyer': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Brianne Jenner': (('Ottawa 2024', 'Ottawa 2024-2025'), '9'),
 'Jincy Roese': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Hayley Scamurra': (('Ottawa 2024', 'Toronto 2024-2025'), '5'),
 'Aneta Tejralová': (('Ottawa 2024', 'Ottawa 2024-2025'), '2'),
 'Zoe Boyd': (('Ottawa 2024', 'Ottawa 2024-2025'), '0'),
 'Natalie Snodgrass': (('Ottawa 2024', 'Ottawa 2024-2025'), '1'),
 'Kateřina Mrázová': (('Ottawa 2024', 'Ottawa 2024-2025'), '6'),
 'Sandra Abstreiter': (('Ottawa 2024', 'Montréal 2024-2025'), '0'),
 'Daryl Watts': (('Ottawa 2024', 'Toronto 2024-2025'), '10'),
 'Emily Clark': (('Ottawa 2024', 'Ottawa 2024-2025'), '4'),
 'Gabbie Hughes': (('Ottawa 2024', 'Ottawa 2024-2025'), '9'),
 'Ashton Bell': (('Ottawa 2024', 'Ottawa 2024-2025'), '2'),
 'Savannah Harmon': (('Ottawa 2024', 'Toronto 2024-2025'), '3'),
 'Emma Maltais': (('Toronto 2024', 'Toronto 2024-2025'), '4'),
 'Kaitlin Willoughby': (('Toronto 2024', 'Toronto 2024-2025'), '0'),
 'Jesse Compher': (('Toronto 2024', 'Toronto 2024-2025'), '1'),
 'Hannah Miller': (('Toronto 2024', 'Toronto 2024-2025'), '7'),
 'Carly Jackson': (('Toronto 2024', 'Toronto 2024-2025'), 0),
 'Rebecca Leslie': (('Toronto 2024', 'Ottawa 2024-2025'), '2'),
 'Blayre Turnbull': (('Toronto 2024', 'Toronto 2024-2025'), '3'),
 'Victoria Bach': (('Toronto 2024', 'Toronto 2024-2025'), '2'),
 'Alexa Vasko': (('Toronto 2024', 'Ottawa 2024-2025'), '2'),
 'Kali Flanagan': (('Toronto 2024', 'Toronto 2024-2025'), '3'),
 'Natalie Spooner': (('Toronto 2024', 'Toronto 2024-2025'), '20'),
 'Olivia Knowles': (('Toronto 2024', 'Toronto 2024-2025'), '0'),
 'Samantha Cogan': (('Toronto 2024', 'Toronto 2024-2025'), '2'),
 'Maggie Connors': (('Toronto 2024', 'Toronto 2024-2025'), '3'),
 'Kristen Campbell': (('Toronto 2024', 'Toronto 2024-2025'), '0'),
 'Jessica Kondas': (('Toronto 2024', 'Toronto 2024-2025'), 0),
 'Allie Munroe': (('Toronto 2024', 'Toronto 2024-2025'), '1'),
 'Renata Fast': (('Toronto 2024', 'Toronto 2024-2025'), '3'),
 'Sarah Nurse': (('Toronto 2024', 'Toronto 2024-2025'), '11'),
 'Jocelyne Larocque': (('Toronto 2024', 'Toronto 2024-2025'), '1')}

In [ ]:
list(player_source_target_2024_goals.items())[:5]

[('Amanda Pelkey', (('Boston 2024', 'Boston 2024-2025'), '1')),
 ('Jessica DiGirolamo', (('Boston 2024', 'Boston 2024-2025'), '0')),
 ('Susanna Tapani', (('Minnesota 2024', 'Boston 2024-2025'), '2')),
 ('Emily Brown', (('Boston 2024', 'Boston 2024-2025'), '1')),
 ('Jamie Lee Rattray', (('Boston 2024', 'Boston 2024-2025'), '3'))]

In [ ]:
player_source_target_2026

{'Laura Kluge': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Susanna Tapani': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Jessie Eldridge': ('Boston 2025-2026', 'Montréal 2026-2027'),
 'Daniela Pejšová': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Jamie Lee Rattray': ('Boston 2025-2026', 'Toronto 2026-2027'),
 'Sophie Shirley': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Zoe Boyd': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Noemi Neubauerová': ('Boston 2025-2026', 'Seattle 2026-2027'),
 'Megan Keller': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Rylind MacKinnon': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Shay Maloney': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Abbey Levy': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Liz Schepers': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Aerin Frankel': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Alina Müller': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Amanda Thiele': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Ella Huber': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Jill Saulnier': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Hadley Hartmetz': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Haley Winn': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Riley Brengman': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Olivia Mobley': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Mia Biotti': ('Boston 2025-2026', 'Detroit 2026-2027'),
 'Loren Gabel': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Taylor Heise': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Klára Hymlárová': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Grace Zumwinkle': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Marlène Boissonnault': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Mae Batherson': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Lee Stecklein': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Claire Butorac': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Peyton Anderson': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Dominique Petrie': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Sidney Morin': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Élizabeth Giguère': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Britta Curl-Salemme': ('Minnesota 2025-2026', 'Detroit 2026-2027'),
 'Maddie Rooney': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Katy Knoll': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Abby Hustler': ('Minnesota 2025-2026', 'Hamilton 2026-2027'),
 'Kendall Cooper': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Samantha Cogan': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Brooke Becker': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Kelly Pannek': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Nicole Hensley': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Natalie Buchbinder': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Madison Bizal': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Hayley Scamurra': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Jessica DiGirolamo': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Laura Stacey': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Abby Roque': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Maureen Murphy': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Kaitlin Willoughby': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Maggie Flaherty': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Nadia Mattivi': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Catherine Dubois': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Lina Ljungblom': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Ann-Renée Desbiens': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Tamara Giaquinto': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Shiann Darkangelo': ('Montréal 2025-2026', 'Detroit 2026-2027'),
 'Amanda Boulier': ('Montréal 2025-2026', 'Boston 2026-2027'),
 'Marie-Philip Poulin': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Dara Greig': ('Montréal 2025-2026', 'Ottawa 2026-2027'),
 'Kati Tabin': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Jade Downie-Landry': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Nicole Gosling': ('Montréal 2025-2026', 'Hamilton 2026-2027'),
 'Alexandra Labelle': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Erin Ambrose': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Megan Warrener': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Natálie Mlýnková': ('Montréal 2025-2026', 'San Jose 2026-2027'),
 'Emmy Fecteau': ('New York 2025-2026', 'New York 2026-2027'),
 'Anne Cherkowski': ('New York 2025-2026', 'San Jose 2026-2027'),
 'Micah Zandee-Hart': ('New York 2025-2026', 'New York 2026-2027'),
 'Lauren Bernard': ('New York 2025-2026', 'New York 2026-2027'),
 'Nicole Vallario': ('New York 2025-2026', 'New York 2026-2027'),
 'Jaime Bourbonnais': ('New York 2025-2026', 'New York 2026-2027'),
 'Elle Hartje': ('New York 2025-2026', 'New York 2026-2027'),
 'Kayle Osborne': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Callie Shanahan': ('New York 2025-2026', 'New York 2026-2027'),
 'Allyson Simpson': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Sarah Fillier': ('New York 2025-2026', 'New York 2026-2027'),
 'Anna Bargman': ('New York 2025-2026', 'New York 2026-2027'),
 'Kaley Doyle': ('New York 2025-2026', 'New York 2026-2027'),
 'Taylor Girard': ('New York 2025-2026', 'Detroit 2026-2027'),
 'Clair DeGeorge': ('New York 2025-2026', 'New York 2026-2027'),
 'Denisa Křížová': ('New York 2025-2026', 'New York 2026-2027'),
 'Dayle Ross': ('New York 2025-2026', 'New York 2026-2027'),
 'Kayla Vespa': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Paetyn Levis': ('New York 2025-2026', 'New York 2026-2027'),
 'Kristýna Kaltounková': ('New York 2025-2026', 'New York 2026-2027'),
 'Maja Nylén Persson': ('New York 2025-2026', 'New York 2026-2027'),
 'Maddi Wheeler': ('New York 2025-2026', 'San Jose 2026-2027'),
 "Kristin O'Neill": ('New York 2025-2026', 'San Jose 2026-2027'),
 'Vita Poniatovskaia': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Fanuza Kadirova': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Brianne Jenner': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Gwyneth Philips': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Sanni Ahola': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Rory Guilday': ('Ottawa 2025-2026', 'San Jose 2026-2027'),
 'Kendra Woodland': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Brooke McQuigge': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Olivia Wallin': ('Ottawa 2025-2026', 'Detroit 2026-2027'),
 'Michela Cava': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Kathryn Reilly': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Rebecca Leslie': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Taylor House': ('Ottawa 2025-2026', 'Boston 2026-2027'),
 'Brooke Hobson': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Emma Greco': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Kateřina Mrázová': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Peyton Hemp': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Alexa Vasko': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Emily Clark': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Gabbie Hughes': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Ronja Savolainen': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Stephanie Markowski': ('Ottawa 2025-2026', 'Detroit 2026-2027'),
 'Jocelyne Larocque': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Emily Brown': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Anna Wilgren': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Cayla Barnes': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Sydney Langseth': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Aneta Tejralová': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Alex Carpenter': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Lyndie Lobdell': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Mariah Keopple': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Theresa Schafzahl': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Jenna Buglioni': ('Seattle 2025-2026', 'Ottawa 2026-2027'),
 'Carly Jackson': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Hannah Bilka': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Lexie Adzija': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Gabrielle David': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Lily Delianedis': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Natalie Snodgrass': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Danielle Serdachny': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Megan Carter': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Julia Gosling': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Corinne Schroeder': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Hannah Murphy': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Jada Habisch': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Mikyla Grant-Mentis': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Brooke Bryant': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Hilary Knight': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Emma Maltais': ('Toronto 2025-2026', 'Montréal 2026-2027'),
 'Anna Kjellbin': ('Toronto 2025-2026', 'Hamilton 2026-2027'),
 'Jesse Compher': ('Toronto 2025-2026', 'Detroit 2026-2027'),
 'Raygan Kirk': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Emma Gentry': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Lauren Messier': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Claire Dalton': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Natalie Spooner': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Daryl Watts': ('Toronto 2025-2026', 'Detroit 2026-2027'),
 'Kali Flanagan': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Kristin Della Rovere': ('Toronto 2025-2026', 'San Jose 2026-2027'),
 'Emma Woods': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Ella Shelton': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Maggie Connors': ('Toronto 2025-2026', 'San Jose 2026-2027'),
 'Jessica Kondas': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Allie Munroe': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Renata Fast': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Elaine Chuli': ('Toronto 2025-2026', 'New York 2026-2027'),
 'Jessie McPherson': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Emerance Maschmeyer': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Tereza Vanišová': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Gabby Rosenthal': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Jenn Gardiner': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Darcie Lappan': ('Vancouver 2025-2026', 'Las Vegas 2026-2027'),
 'Mellissa Channell-Watkins': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Abby Boreen': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Hannah Miller': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Mannon McMahon': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sophie Jaques': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Katie Chan': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Izzy Daniel': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Anna Segedi': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Nina Jobst-Smith': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Kristen Campbell': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sydney Bard': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Ashton Bell': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sarah Nurse': ('Vancouver 2025-2026', 'Vancouver 2026-2027')}

In [ ]:
player_source_target_2026["Hilary Knight"]

('Seattle 2025-2026', 'Detroit 2026-2027')

In [ ]:
player_source_target_dicts_list_goals = [player_source_target_2024_goals, player_source_target_2025_goals, player_source_target_2026_goals]

In [ ]:
player_source_target_2026

{'Laura Kluge': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Susanna Tapani': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Jessie Eldridge': ('Boston 2025-2026', 'Montréal 2026-2027'),
 'Daniela Pejšová': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Jamie Lee Rattray': ('Boston 2025-2026', 'Toronto 2026-2027'),
 'Sophie Shirley': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Zoe Boyd': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Noemi Neubauerová': ('Boston 2025-2026', 'Seattle 2026-2027'),
 'Megan Keller': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Rylind MacKinnon': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Shay Maloney': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Abbey Levy': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Liz Schepers': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Aerin Frankel': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Alina Müller': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Amanda Thiele': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Ella Huber': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Jill Saulnier': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Hadley Hartmetz': ('Boston 2025-2026', 'San Jose 2026-2027'),
 'Haley Winn': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Riley Brengman': ('Boston 2025-2026', 'Hamilton 2026-2027'),
 'Olivia Mobley': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Mia Biotti': ('Boston 2025-2026', 'Detroit 2026-2027'),
 'Loren Gabel': ('Boston 2025-2026', 'Boston 2026-2027'),
 'Taylor Heise': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Klára Hymlárová': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Grace Zumwinkle': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Marlène Boissonnault': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Mae Batherson': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Lee Stecklein': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Claire Butorac': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Peyton Anderson': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Dominique Petrie': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Sidney Morin': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Élizabeth Giguère': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Britta Curl-Salemme': ('Minnesota 2025-2026', 'Detroit 2026-2027'),
 'Maddie Rooney': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Katy Knoll': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Abby Hustler': ('Minnesota 2025-2026', 'Hamilton 2026-2027'),
 'Kendall Cooper': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Samantha Cogan': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Brooke Becker': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Kelly Pannek': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Nicole Hensley': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Natalie Buchbinder': ('Minnesota 2025-2026', 'Minnesota 2026-2027'),
 'Madison Bizal': ('Minnesota 2025-2026', 'Las Vegas 2026-2027'),
 'Hayley Scamurra': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Jessica DiGirolamo': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Laura Stacey': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Abby Roque': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Maureen Murphy': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Kaitlin Willoughby': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Maggie Flaherty': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Nadia Mattivi': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Catherine Dubois': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Lina Ljungblom': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Ann-Renée Desbiens': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Tamara Giaquinto': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Shiann Darkangelo': ('Montréal 2025-2026', 'Detroit 2026-2027'),
 'Amanda Boulier': ('Montréal 2025-2026', 'Boston 2026-2027'),
 'Marie-Philip Poulin': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Dara Greig': ('Montréal 2025-2026', 'Ottawa 2026-2027'),
 'Kati Tabin': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Jade Downie-Landry': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Nicole Gosling': ('Montréal 2025-2026', 'Hamilton 2026-2027'),
 'Alexandra Labelle': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Erin Ambrose': ('Montréal 2025-2026', 'Las Vegas 2026-2027'),
 'Megan Warrener': ('Montréal 2025-2026', 'Montréal 2026-2027'),
 'Natálie Mlýnková': ('Montréal 2025-2026', 'San Jose 2026-2027'),
 'Emmy Fecteau': ('New York 2025-2026', 'New York 2026-2027'),
 'Anne Cherkowski': ('New York 2025-2026', 'San Jose 2026-2027'),
 'Micah Zandee-Hart': ('New York 2025-2026', 'New York 2026-2027'),
 'Lauren Bernard': ('New York 2025-2026', 'New York 2026-2027'),
 'Nicole Vallario': ('New York 2025-2026', 'New York 2026-2027'),
 'Jaime Bourbonnais': ('New York 2025-2026', 'New York 2026-2027'),
 'Elle Hartje': ('New York 2025-2026', 'New York 2026-2027'),
 'Kayle Osborne': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Callie Shanahan': ('New York 2025-2026', 'New York 2026-2027'),
 'Allyson Simpson': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Sarah Fillier': ('New York 2025-2026', 'New York 2026-2027'),
 'Anna Bargman': ('New York 2025-2026', 'New York 2026-2027'),
 'Kaley Doyle': ('New York 2025-2026', 'New York 2026-2027'),
 'Taylor Girard': ('New York 2025-2026', 'Detroit 2026-2027'),
 'Clair DeGeorge': ('New York 2025-2026', 'New York 2026-2027'),
 'Denisa Křížová': ('New York 2025-2026', 'New York 2026-2027'),
 'Dayle Ross': ('New York 2025-2026', 'New York 2026-2027'),
 'Kayla Vespa': ('New York 2025-2026', 'Hamilton 2026-2027'),
 'Paetyn Levis': ('New York 2025-2026', 'New York 2026-2027'),
 'Kristýna Kaltounková': ('New York 2025-2026', 'New York 2026-2027'),
 'Maja Nylén Persson': ('New York 2025-2026', 'New York 2026-2027'),
 'Maddi Wheeler': ('New York 2025-2026', 'San Jose 2026-2027'),
 "Kristin O'Neill": ('New York 2025-2026', 'San Jose 2026-2027'),
 'Vita Poniatovskaia': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Fanuza Kadirova': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Brianne Jenner': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Gwyneth Philips': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Sanni Ahola': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Rory Guilday': ('Ottawa 2025-2026', 'San Jose 2026-2027'),
 'Kendra Woodland': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Brooke McQuigge': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Olivia Wallin': ('Ottawa 2025-2026', 'Detroit 2026-2027'),
 'Michela Cava': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Kathryn Reilly': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Rebecca Leslie': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Taylor House': ('Ottawa 2025-2026', 'Boston 2026-2027'),
 'Brooke Hobson': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Emma Greco': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Kateřina Mrázová': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Peyton Hemp': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Alexa Vasko': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Emily Clark': ('Ottawa 2025-2026', 'Hamilton 2026-2027'),
 'Gabbie Hughes': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Ronja Savolainen': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Stephanie Markowski': ('Ottawa 2025-2026', 'Detroit 2026-2027'),
 'Jocelyne Larocque': ('Ottawa 2025-2026', 'Ottawa 2026-2027'),
 'Emily Brown': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Anna Wilgren': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Cayla Barnes': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Sydney Langseth': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Aneta Tejralová': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Alex Carpenter': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Lyndie Lobdell': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Mariah Keopple': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Theresa Schafzahl': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Jenna Buglioni': ('Seattle 2025-2026', 'Ottawa 2026-2027'),
 'Carly Jackson': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Hannah Bilka': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Lexie Adzija': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Gabrielle David': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Lily Delianedis': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Natalie Snodgrass': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Danielle Serdachny': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Megan Carter': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Julia Gosling': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Corinne Schroeder': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Hannah Murphy': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Jada Habisch': ('Seattle 2025-2026', 'Las Vegas 2026-2027'),
 'Mikyla Grant-Mentis': ('Seattle 2025-2026', 'Seattle 2026-2027'),
 'Brooke Bryant': ('Seattle 2025-2026', 'San Jose 2026-2027'),
 'Hilary Knight': ('Seattle 2025-2026', 'Detroit 2026-2027'),
 'Emma Maltais': ('Toronto 2025-2026', 'Montréal 2026-2027'),
 'Anna Kjellbin': ('Toronto 2025-2026', 'Hamilton 2026-2027'),
 'Jesse Compher': ('Toronto 2025-2026', 'Detroit 2026-2027'),
 'Raygan Kirk': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Emma Gentry': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Lauren Messier': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Claire Dalton': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Natalie Spooner': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Daryl Watts': ('Toronto 2025-2026', 'Detroit 2026-2027'),
 'Kali Flanagan': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Kristin Della Rovere': ('Toronto 2025-2026', 'San Jose 2026-2027'),
 'Emma Woods': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Ella Shelton': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Maggie Connors': ('Toronto 2025-2026', 'San Jose 2026-2027'),
 'Jessica Kondas': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Allie Munroe': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Renata Fast': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Elaine Chuli': ('Toronto 2025-2026', 'New York 2026-2027'),
 'Jessie McPherson': ('Toronto 2025-2026', 'Toronto 2026-2027'),
 'Emerance Maschmeyer': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Tereza Vanišová': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Gabby Rosenthal': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Jenn Gardiner': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Darcie Lappan': ('Vancouver 2025-2026', 'Las Vegas 2026-2027'),
 'Mellissa Channell-Watkins': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Abby Boreen': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Hannah Miller': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Mannon McMahon': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sophie Jaques': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Katie Chan': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Izzy Daniel': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Anna Segedi': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Nina Jobst-Smith': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Kristen Campbell': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sydney Bard': ('Vancouver 2025-2026', 'Detroit 2026-2027'),
 'Ashton Bell': ('Vancouver 2025-2026', 'Vancouver 2026-2027'),
 'Sarah Nurse': ('Vancouver 2025-2026', 'Vancouver 2026-2027')}

# Generate input for Sankey Diagram
Create csvs with columns source, target, player_list, player_count, goals, and value, where value corresponds to the band width for the sankey diagram.

```
create_transition_csv_for_column(transition_df, 'player_transitions_goals.csv', 'goals')
create_transition_csv_for_column(transition_df, 'player_transitions.csv', 'player_count')
```

In [ ]:
from collections import defaultdict
import itertools

In [ ]:
# Generate player count, player lists, goals for every source, target tuple
source_target_count = defaultdict(int)
source_target_player_lists = defaultdict(list)
source_target_goals = defaultdict(int)

source_target_info = defaultdict(dict)


for player_source_target_dict in player_source_target_dicts_list_goals:
    for player_name, source_target_goals_tuple in player_source_target_dict.items():
        source_target_tuple, goals = source_target_goals_tuple

        if source_target_info.get(source_target_tuple) is None:
            source_target_info[source_target_tuple] = {"player_count": 0, "player_list": [], "goals":0}


        source_target_info[source_target_tuple]["player_count"] +=1
        source_target_info[source_target_tuple]["player_list"].append(player_name)
        source_target_info[source_target_tuple]["goals"] += int(goals)

        source_target_count[source_target_tuple] += 1
        source_target_player_lists[source_target_tuple].append(player_name)
        source_target_goals[source_target_tuple] += int(goals)

In [ ]:
# source target info
display(dict(itertools.islice(source_target_info.items(), 5)))

{('Boston 2024', 'Boston 2024-2025'): {'player_count': 15,
  'player_list': ['Amanda Pelkey',
   'Jessica DiGirolamo',
   'Emily Brown',
   'Jamie Lee Rattray',
   'Hannah Brandt',
   'Sophie Shirley',
   'Emma Söderberg',
   'Kelly Babstock',
   'Sidney Morin',
   'Megan Keller',
   'Theresa Schafzahl',
   'Alina Müller',
   'Aerin Frankel',
   'Loren Gabel',
   'Hilary Knight'],
  'goals': 36},
 ('Minnesota 2024', 'Boston 2024-2025'): {'player_count': 2,
  'player_list': ['Susanna Tapani', 'Emma Greco'],
  'goals': 2},
 ('Ottawa 2024', 'Ottawa 2024-2025'): {'player_count': 13,
  'player_list': ['Samantha Isbell',
   'Shiann Darkangelo',
   'Tereza Vanišová',
   'Emerance Maschmeyer',
   'Brianne Jenner',
   'Jincy Roese',
   'Aneta Tejralová',
   'Zoe Boyd',
   'Natalie Snodgrass',
   'Kateřina Mrázová',
   'Emily Clark',
   'Gabbie Hughes',
   'Ashton Bell'],
  'goals': 33},
 ('Minnesota 2024', 'Minnesota 2024-2025'): {'player_count': 16,
  'player_list': ['Sophie Jaques',
   'Taylor Heise',
   'Grace Zumwinkle',
   'Mellissa Channell-Watkins',
   'Maggie Flaherty',
   'Lee Stecklein',
   'Claire Butorac',
   'Michela Cava',
   'Liz Schepers',
   'Maddie Rooney',
   'Kendall Coyne Schofield',
   'Denisa Křížová',
   'Kelly Pannek',
   'Brooke Bryant',
   'Nicole Hensley',
   'Natalie Buchbinder'],
  'goals': 42},
 ('Ottawa 2024', 'Boston 2024-2025'): {'player_count': 1,
  'player_list': ['Lexie Adzija'],
  'goals': 1}}

In [ ]:
# source target count
display(dict(itertools.islice(source_target_count.items(), 5)))

{('Boston 2024', 'Boston 2024-2025'): 15,
 ('Minnesota 2024', 'Boston 2024-2025'): 2,
 ('Ottawa 2024', 'Ottawa 2024-2025'): 13,
 ('Minnesota 2024', 'Minnesota 2024-2025'): 16,
 ('Ottawa 2024', 'Boston 2024-2025'): 1}

In [ ]:
# source target player lists
display(dict(itertools.islice(source_target_player_lists.items(), 2)))

{('Boston 2024', 'Boston 2024-2025'): ['Amanda Pelkey',
  'Jessica DiGirolamo',
  'Emily Brown',
  'Jamie Lee Rattray',
  'Hannah Brandt',
  'Sophie Shirley',
  'Emma Söderberg',
  'Kelly Babstock',
  'Sidney Morin',
  'Megan Keller',
  'Theresa Schafzahl',
  'Alina Müller',
  'Aerin Frankel',
  'Loren Gabel',
  'Hilary Knight'],
 ('Minnesota 2024', 'Boston 2024-2025'): ['Susanna Tapani', 'Emma Greco']}

In [ ]:
# source target goals
display(dict(itertools.islice(source_target_goals.items(), 5)))

{('Boston 2024', 'Boston 2024-2025'): 36,
 ('Minnesota 2024', 'Boston 2024-2025'): 2,
 ('Ottawa 2024', 'Ottawa 2024-2025'): 33,
 ('Minnesota 2024', 'Minnesota 2024-2025'): 42,
 ('Ottawa 2024', 'Boston 2024-2025'): 1}

In [ ]:
def create_transition_df():
  data_for_df = []

  for (source, target), info in source_target_info.items():
      data_for_df.append({
          'source': source,
          'target': target,
          'player_list': info["player_list"],
          'player_count': info["player_count"],
          'goals': info["goals"]
      })

  transitions_df = pd.DataFrame(data_for_df)
  return transitions_df

In [ ]:
transition_df = create_transition_df()

In [ ]:
transition_df.head()

,source,target,player_list,player_count,goals
0,Boston 2024,Boston 2024-2025,"[Amanda Pelkey, Jessica DiGirolamo, Emily Brow...",15,36
1,Minnesota 2024,Boston 2024-2025,"[Susanna Tapani, Emma Greco]",2,2
2,Ottawa 2024,Ottawa 2024-2025,"[Samantha Isbell, Shiann Darkangelo, Tereza Va...",13,33
3,Minnesota 2024,Minnesota 2024-2025,"[Sophie Jaques, Taylor Heise, Grace Zumwinkle,...",16,42
4,Ottawa 2024,Boston 2024-2025,[Lexie Adzija],1,1

In [ ]:
# Create a csv where the value column corresponds to the specified column
def create_transition_df_and_csv_for_column(transition_df, csv_filename, column):
  csv_df = transition_df.copy()

  # create value column
  csv_df['value'] = csv_df[column]

  # Save to CSV
  csv_df.to_csv(csv_filename, index=False)
  print(f"Data successfully saved to {csv_filename}")

  return csv_df

In [ ]:
transition_df_counts = create_transition_df_and_csv_for_column(transition_df, 'player_transitions.csv', 'player_count')

Data successfully saved to player_transitions.csv

In [ ]:
transition_df_goals = create_transition_df_and_csv_for_column(transition_df, 'player_transitions_goals.csv', 'goals')

Data successfully saved to player_transitions_goals.csv

# Stacked Bar Chart: Value

In [ ]:
import altair as alt

In [ ]:
# Define custom colors based on the provided JavaScript with full city names
custom_colors = {
    "Seattle": "teal",
    "Toronto": "RoyalBlue",
    "Boston": "green",
    "Montréal": "maroon",
    "Hamilton": "gold",
    "Detroit": "black",
    "Las Vegas": "Olive",
    "San Jose": "DeepSkyBlue",
    "Minnesota": "MediumSlateBlue",
    "Ottawa": "Crimson",
    "Vancouver": "MediumBlue",
    "New York": "LightSeaGreen",
}

# Create lists for domain (team names) and range (colors)
color_domain = list(custom_colors.keys())
color_range = list(custom_colors.values())

In [ ]:
def create_bar_chart(transition_df, vertical_label):

  # Filter for transitions originating from the 2025-2026 season
  df_2025_2026_transitions = transition_df[transition_df['source'].str.contains('2025-2026')].copy()

  # Extract source and target team names (full city names)
  df_2025_2026_transitions['source_team'] = df_2025_2026_transitions['source'].apply(lambda x: ' '.join(x.split(' ')[:-1]))
  df_2025_2026_transitions['target_team'] = df_2025_2026_transitions['target'].apply(lambda x: ' '.join(x.split(' ')[:-1]))

  # Calculate players lost by each 2025-2026 team
  lost_players_by_team = {}

  # Get all unique source teams for 2025-2026 season
  source_teams_2025_2026 = df_2025_2026_transitions['source'].unique()

  for team_full_name in source_teams_2025_2026:
      source_team_name = ' '.join(team_full_name.split(' ')[:-1]) # e.g., 'Boston' or 'New York'

      # Filter transitions for the current source team
      team_transitions = df_2025_2026_transitions[df_2025_2026_transitions['source'] == team_full_name]

      # Sum players where the target team is different from the source team
      total_lost = team_transitions[team_transitions['target_team'] != source_team_name]['value'].sum()
      lost_players_by_team[source_team_name] = total_lost

  # print("Number of players lost by each 2025-2026 team:")
  # for team, count in lost_players_by_team.items():
  #     print(f"{team}: {count} players lost")


  # Define a fixed sort order for target teams for consistent visualization
  target_team_sort_order = {
      'Detroit': 1,
      'Hamilton': 2,
      'Las Vegas': 3,
      'San Jose': 4,
      'Boston': 5,
      'Minnesota': 6,
      'Montréal': 7,
      'New York': 8,
      'Ottawa': 9,
      'Seattle': 10,
      'Toronto': 11,
      'Vancouver': 12,
  }

  # Create a sorting key to put the original team at the bottom, then expansion teams, then others
  df_2025_2026_transitions['sort_order'] = df_2025_2026_transitions.apply(
      lambda row: 0 if row['source_team'] == row['target_team'] else target_team_sort_order.get(row['target_team'], len(target_team_sort_order) + 1),
      axis=1
  )

  # Create the stacked bar graph with custom colors and sorting
  chart = alt.Chart(df_2025_2026_transitions).mark_bar().encode(
      x=alt.X('source_team:N', axis=alt.Axis(title='Source Team')),
      y=alt.Y('value:Q', axis=alt.Axis(title=vertical_label)),
      color=alt.Color('target_team:N', title='Target Team',
                      scale=alt.Scale(domain=color_domain, range=color_range)),
      order=alt.Order('sort_order:Q', sort='ascending'), # Sort by the new column
      tooltip=['source_team', 'target_team', 'value', alt.Tooltip('player_list', title='Players')]
  ).properties(
      title='Player Transitions from Source Teams (by Target Team)'
  )

  # for source_team in lost_players_by_team.keys():
  #   print(f"\nPlayers lost by {source_team}:")

  #   # Filter for transitions from this source team to a different target team
  #   lost_transitions = df_2025_2026_transitions[
  #       (df_2025_2026_transitions['source_team'] == source_team) &
  #       (df_2025_2026_transitions['target_team'] != source_team)
  #   ]

  #   if lost_transitions.empty:
  #       print("  No players lost to other teams.")
  #   else:
  #       for index, row in lost_transitions.iterrows():
  #           target_team = row['target_team']
  #           players = row['player_list']
  #           if players:
  #               print(f"  To {target_team}: {', '.join(players)}")

  return chart

In [ ]:
player_counts_chart = create_bar_chart(transition_df_counts, "Number of Players")

In [ ]:
player_counts_chart

alt.Chart(...)

In [ ]:
player_goals_chart = create_bar_chart(transition_df_goals, "Goals Scored")

In [ ]:
player_goals_chart

alt.Chart(...)

In [279]:
def create_expansion_target_bar_chart(transition_df, vertical_label):
  # Define the target expansion teams
  expansion_target_teams = ['Hamilton', 'Detroit', 'Las Vegas', 'San Jose']

  # Filter for transitions *to* the 2026-2027 season
  df_2026_2027_targets = transition_df[transition_df['target'].str.contains('2026-2027')].copy()

  # Extract source and target team names (full city names)
  df_2026_2027_targets['source_team'] = df_2026_2027_targets['source'].apply(lambda x: ' '.join(x.split(' ')[:-1]))
  df_2026_2027_targets['target_team'] = df_2026_2027_targets['target'].apply(lambda x: ' '.join(x.split(' ')[:-1]))

  # Further filter to only include transitions to the specified expansion teams
  df_expansion_targets = df_2026_2027_targets[
      df_2026_2027_targets['target_team'].isin(expansion_target_teams)
  ].copy()

  # Define a consistent order for the x-axis (target expansion teams)
  target_team_x_order = [team for team in expansion_target_teams if team in df_expansion_targets['target_team'].unique()]

  # Create the stacked bar chart with custom colors
  chart = alt.Chart(df_expansion_targets).mark_bar().encode(
      # X-axis: Target expansion teams
      x=alt.X('target_team:N', axis=alt.Axis(title='Target Expansion Team'), sort=target_team_x_order),
      # Y-axis: Value (player count or goals)
      y=alt.Y('value:Q', axis=alt.Axis(title=vertical_label)),
      # Color: Source teams
      color=alt.Color('source_team:N', title='Source Team',
                      scale=alt.Scale(domain=color_domain, range=color_range)),
      tooltip=[
          alt.Tooltip('source_team', title='Source Team'),
          alt.Tooltip('target_team', title='Target Team'),
          alt.Tooltip('value:Q', title=vertical_label),
          alt.Tooltip('player_list', title='Players')
      ]
  ).properties(
      title=f'Expansion Team Makeup - {vertical_label}'
  )

  return chart

In [280]:
create_expansion_target_bar_chart(transition_df_counts, "Number of Players")

alt.Chart(...)

In [281]:
create_expansion_target_bar_chart(transition_df_goals, "Goals Scored")

alt.Chart(...)

# Vertical Diverging Stacked Bar Chart: Value Kept vs. Lost (2025-2026 Season)

In [ ]:
def diverging_stacked_bars(transition_df, title, ascending=False):
  # Filter for transitions originating from the 2025-2026 season
  df_2025_2026_transitions = transition_df[transition_df['source'].str.contains('2025-2026')].copy()

  # Extract source and target team names (full city names)
  df_2025_2026_transitions['source_team'] = df_2025_2026_transitions['source'].apply(lambda x: ' '.join(x.split(' ')[:-1]))
  df_2025_2026_transitions['target_team'] = df_2025_2026_transitions['target'].apply(lambda x: ' '.join(x.split(' ')[:-1]))

  # Create a copy to avoid modifying the original DataFrame used by the first chart
  df_diverging = df_2025_2026_transitions.copy()

  # Create a 'display_value' for the diverging chart:
  # Positive for players kept, negative for players lost
  df_diverging['display_value'] = df_diverging.apply(
      lambda row: row['value'] if row['source_team'] == row['target_team'] else -row['value'],
      axis=1
  )

  # Calculate players lost by each 2025-2026 team (for sorting)
  value_lost = df_diverging[df_diverging['source_team'] != df_diverging['target_team']].groupby('source_team')['value'].sum().reset_index()
  value_lost.rename(columns={'value': 'players_lost'}, inplace=True)

  # Get the order of source teams based on total players lost
  sorted_source_teams_by_lost = value_lost.sort_values(by='players_lost', ascending=ascending)['source_team'].tolist()

  # Define a fixed sort order for target teams for consistent visualization (from create_bar_chart)
  target_team_sort_order = {
      'Detroit': 1,
      'Hamilton': 2,
      'Las Vegas': 3,
      'San Jose': 4,
      'Boston': 5,
      'Minnesota': 6,
      'Montréal': 7,
      'New York': 8,
      'Ottawa': 9,
      'Seattle': 10,
      'Toronto': 11,
      'Vancouver': 12,
  }

  # Create a sorting key to put the original team at the bottom, then expansion teams, then others
  df_diverging['sort_order'] = df_diverging.apply(
      lambda row: 0 if row['source_team'] == row['target_team'] else target_team_sort_order.get(row['target_team'], len(target_team_sort_order) + 1),
      axis=1
  )

  # Define the base chart with a vertical orientation
  base_vertical = alt.Chart(df_diverging).encode(
      x=alt.X('source_team:N',
              axis=alt.Axis(title='Source Team', labelAngle=-45, titleFontSize=20, labelFontSize=18),
              sort=sorted_source_teams_by_lost), # Sort x-axis by players lost
      tooltip=['source_team', 'target_team', 'value', alt.Tooltip('player_list', title='Players')] # Keep original 'value' for tooltip
  )

  # Create the stacked bars
  vertical_bar_chart = base_vertical.mark_bar().encode(
      y=alt.Y('display_value:Q',
              axis=alt.Axis(title=title + ' (Kept: Positive, Lost: Negative)', format='d', titleFontSize=20, labelFontSize=18)),
      color=alt.Color('target_team:N', title='Target Team',
                      scale=alt.Scale(domain=color_domain, range=color_range),
                      legend=alt.Legend(titleFontSize=20, labelFontSize=18)), # Increase legend title and label font sizes
      # Use the same sort_order to maintain consistent stacking within each bar
      # For the diverging chart, this sorts from the central axis outwards.
      order=alt.Order('sort_order:Q', sort='ascending')
  ).properties(
      title=alt.Title(text=[title +' Kept vs Lost For Existing', 'PWHL Teams in the 2026 Expansion'], anchor='middle', fontSize=24),
      width=400, # Restored width to 400
      height=500  # Restored height to 500
  )

  return vertical_bar_chart

In [ ]:
players_lost_chart = diverging_stacked_bars(transition_df_counts, "Number of Players", ascending=True)

In [ ]:
players_lost_chart

alt.Chart(...)

In [ ]:
goals_lost_chart = diverging_stacked_bars(transition_df_goals, "Number of Goals", ascending=True)

In [ ]:
goals_lost_chart

alt.Chart(...)

## 2025-2026 Goals For and Against

In [ ]:
def get_standings_for_season(season_id):
  standings_response = requests.get("https://lscluster.hockeytech.com/feed/index.php?feed=modulekit&view=statviewtype&stat=conference&type=standings&season_id="+str(season_id) +"&key=446521baf8c38984&client_code=pwhl")
  if standings_response.status_code != 200:
    return None

  standings_json = standings_response.json()
  standings_json_stats = standings_json["SiteKit"]["Statviewtype"]


  # Load the JSON file into a DataFrame
  standings_df = pd.json_normalize(standings_json_stats[1:])
  standings_df_short = standings_df[['team_id', 'city', 'nickname', 'goals_for', 'goals_against']]

  return standings_df_short

In [ ]:
standings_2025 = get_standings_for_season(season_to_id_map["2025-2026"])

In [269]:
alt.Chart(standings_2025).mark_bar().encode(
    x=alt.X('city:N', axis=alt.Axis(title='Team'), sort=alt.EncodingSortField(field="goals_for", op="sum", order='ascending')),
    y=alt.Y('goals_for:Q', axis=alt.Axis(title='Goals For')),
    color=alt.Color('city:N', scale=alt.Scale(domain=color_domain, range=color_range), title='Team'),
    tooltip=['city', 'goals_for']
).properties(
    title='Goals For by Team (2025-2026 Season)'
)

alt.Chart(...)

In [268]:
alt.Chart(standings_2025).mark_bar().encode(
    x=alt.X('city:N', axis=alt.Axis(title='Team'), sort=alt.EncodingSortField(field="goals_against", op="sum", order='ascending')),
    y=alt.Y('goals_against:Q', axis=alt.Axis(title='Goals Against')),
    color=alt.Color('city:N', scale=alt.Scale(domain=color_domain, range=color_range), title='Team'),
    tooltip=['city', 'goals_against']
).properties(
    title='Goals Against by Team (2025-2026 Season)'
)

alt.Chart(...)

# For every player, generate a list of transitions

In [ ]:
from collections import defaultdict

player_transitions_map = defaultdict(list)

for year_dict in player_source_target_dicts_list:
    for player, source_target_tuple in year_dict.items():
        player_transitions_map[player].append(source_target_tuple)

# Display some examples
display("Hilary Knight's transitions:")
display(player_transitions_map.get('Hilary Knight'))

display("Sophie Shirley's transitions:")
display(player_transitions_map.get('Sophie Shirley'))

"Hilary Knight's transitions:"

[('Boston 2024', 'Boston 2024-2025'),
 ('Boston 2024-2025', 'Seattle 2025-2026'),
 ('Seattle 2025-2026', 'Detroit 2026-2027')]

"Sophie Shirley's transitions:"

[('Boston 2024', 'Boston 2024-2025'),
 ('Boston 2024-2025', 'Boston 2025-2026'),
 ('Boston 2025-2026', 'Boston 2026-2027')]

In [ ]:
import json

# Convert the defaultdict to a regular dictionary for JSON serialization
player_transitions_map_regular_dict = {player: list(transitions) for player, transitions in player_transitions_map.items()}

json_filename = 'player_transitions_map.json'
with open(json_filename, 'w') as f:
    json.dump(player_transitions_map_regular_dict, f, indent=4)

print(f"'player_transitions_map' successfully saved to {json_filename}")

'player_transitions_map' successfully saved to player_transitions_map.json